Vizzuality/trase

app/controllers/map_controller.rb, app/serializers/dimension_serializer.rb, db/migrate/20170526103500_add_context_layer_color_scale.rb, db/structure.sql
Follows up on https://github.com/Vizzuality/TRASE-frontend/pull/370/files by adding the needed info on the DB/API side
=> Add color scales to context layers

app/models/flow_stats_for_node.rb, app/models/place_attributes.rb
https://basecamp.com/1756858/projects/12498794/todos/308610507
depends on https://github.com/Vizzuality/TRASE-frontend/pull/425
=> Add is_domestic_consumption flag to top consumer in place profile

app/models/place_attributes.rb
https://basecamp.com/1756858/projects/12498794/todos/308419058
=> Return soy production value separately

app/models/actor_attributes.rb, app/models/ind.rb, app/models/place_attributes.rb, app/models/quant.rb, lib/tasks/populate_context_indicators.rake, spec/controllers/indicators_controller_spec.rb, spec/controllers/place_factsheet_controller_spec.rb, spec/models/flow_download_query_builder_spec.rb, spec/support/brazil_soy_indicators.rb, spec/support/two_flows_context.rb
https://github.com/sei-international/TRASE/blob/new-data-2017/DB/mapping_variables
some quants/inds were renamed, others moved around, so it's api changing time!
=> Update profile page logic for new data

app/models/flow_download.rb, app/models/flow_download_query_builder.rb, spec/models/flow_download_query_builder_spec.rb
https://basecamp.com/1756858/projects/12498794/todos/325801097
=> Do not discriminate against other types of commodities in downloads

db/migrate/20170929120908_update_materialized_flows_to_version_7.rb, db/structure.sql, db/views/materialized_flows_v07.sql, db/views/node_flows_v05.sql, spec/models/flow_download_query_builder_spec.rb
`materialized_flows` simplified significantly by removing the TOTAL aggregations
=> DATA PORTAL: Issue with replication of values

app/models/actor_attributes.rb, app/models/flow_stats_for_node.rb
Please merge after #39 - which implements the `node#flow_values` method.
This restores calculation of sustainability indicators from flow rather than node values.
https://basecamp.com/1756858/projects/12498794/todos/325801068
=> ACTOR: Calculation of sustainability indicator totals for top sources

app/models/place_attributes.rb
This to fix soy land in header & description text
619,984,117 Ha -> 619,984 Ha
=> Removed conversion which is no longer required since data has been fixed

app/models/flow_download_query_builder.rb
https://basecamp.com/1756858/projects/12498794/todos/325801097
=> Set commodity type in downloads to commodity + ' equivalents'

app/serializers/recolor_by_serializer.rb, app/serializers/resize_by_serializer.rb, db/migrate/20171004102919_add_tooltip_text_to_recolor_by_resize_by.rb, db/structure.sql, spec/controllers/structure_controller_spec.rb, spec/factories/context_recolor_by.rb, spec/factories/context_resize_by.rb, spec/support/brazil_recolor_by.rb, spec/support/brazil_resize_by.rb, spec/support/inds.rb
blocked by https://basecamp.com/1756858/projects/12498794/todos/326726600
=> Recolor by and resize by tooltips in database

app/models/place_attributes.rb
Clement confirmed we can remove this
=> Remove reference to old cattle heads quant

frontend/scripts/containers/tool/nav/country-commodity.container.js, frontend/scripts/react-components/tool/nav/country-commodity.component.js, frontend/scripts/react-components/tool/nav/dimensional-selector.component.js, frontend/styles/components/tool/country-commodities-react.scss, frontend/styles/components/tool/dimensional-selector-react.scss
- New country-commodity selector.
- New component `<DimensionalSelector />` that allows the user to select data in without an explicit order.
=> Feat: dimensional selector

app/controllers/api/v2/nodes_controller.rb, app/serializers/get_all_nodes_serializer.rb, spec/support/schemas/all_nodes.json
Addresses https://github.com/Vizzuality/trase/issues/106
=> Add main node id to get_all_nodes

app/controllers/api/v3/newsletter_subscriptions_controller.rb, config/routes.rb, doc/swagger.yaml
This is a very simple feature, as it's just copying it from V2.
=> Added the v3 endpoint for newsleters_subscriptions

frontend/scripts/pages/profile-actor.page.js, frontend/scripts/pages/profile-place.page.js
=> Capitalize municipality/actor name in profile page

.rubocop.yml, app/controllers/api/v3/nodes_controller.rb, app/serializers/api/v3/nodes/node_serializer.rb, config/routes.rb, doc/swagger.yaml, frontend/scripts/pages/profiles.page.js, frontend/scripts/utils/getURLFromParams.js, lib/schema_revamp.rb, spec/factories/context_filter_by.rb, spec/responses/api/v3/flows_spec.rb, spec/support/contexts/brazil/brazil_context_nodes.rb, spec/support/contexts/brazil/brazil_contexts.rb, spec/support/contexts/brazil/brazil_soy_indicators.rb, spec/support/contexts/node_types.rb, spec/support/gold_master_urls.yml, spec/support/schemas/all_nodes.json, spec/version_migration/get_all_nodes_spec.rb, spec/version_migration/get_contexts_spec.rb
This feature is not complete as I wasn't able to test it.
When including `brazil contexts` I get an error creating the schemaRevamp as follows:
```
NoMethodError: undefined method `[]' for nil:NilClass
./lib/schema_revamp.rb:633:in `block in insert_chart'
```
@agnessa would you mind taking a lot at it?
=> First version of the V3 endpoints for Nodes

frontend/html/includes/_search.ejs, frontend/html/profile-actor.ejs, frontend/html/profile-place.ejs, frontend/html/profiles.ejs, frontend/scripts/pages/profile-actor.page.js, frontend/scripts/pages/profile-place.page.js, frontend/scripts/pages/profiles.page.js, frontend/styles/layouts/l-profiles.scss
Fixes #117 
- When loading data on profile search page, it now shows a message on failure
- On the same page, the CSS is no longer broken while data is loading
- On profile pages (actor and place) an error message is displayed in case data fails to load
=> Styling details and error handling on profile pages

frontend/html/profile-place.ejs, frontend/scripts/pages/profile-place.page.js, frontend/scripts/react-components/profiles/mini-sankey.component.js, frontend/styles/components/profiles/mini-sankey.scss, frontend/styles/layouts/l-profile-place.scss
Replaces Top and Chord components with Mini Sankeys.
Currently uses dummy data, will need to be implemented on the backend, or data existing on the current endpoint must be converted on the frontend.
**TO DO**
=> Mini sankey on place profile pages

.rubocop_todo.yml, Gemfile, Gemfile.lock, app/admin/dashboard.rb, app/admin/post.rb, app/admin/site_dive.rb, app/admin/testimonial.rb, app/admin/user.rb, app/controllers/content/testimonials_controller.rb, app/models/content/testimonial.rb, app/serializers/testimonial_serializer.rb, config/routes.rb, db_content/migrate/20180117084134_create_testimonials.rb, db_content/migrate/20180117084618_add_image_to_testimonials.rb, db_content/structure.sql
Partially addresses https://github.com/Vizzuality/trase/issues/178
=> Add testimonials model to content api

frontend/package-lock.json, frontend/scripts/pages/profile-actor.page.jsx, frontend/scripts/pages/profile-place.page.jsx, frontend/scripts/react-components/profiles/chord.component.jsx, frontend/scripts/react-components/profiles/line.component.jsx, frontend/scripts/react-components/profiles/map.component.jsx, frontend/scripts/react-components/profiles/multi-table.component.jsx, frontend/scripts/react-components/profiles/scatterplot.component.jsx
This reverts commit 73716f37d0961aac1919d7384391f61d49e8227b.
=> Revert "fix: adds id prop to d3 chart components"

.gitignore, frontend/scripts/pages/home.page.jsx, frontend/scripts/pages/profile-actor.page.jsx, frontend/scripts/pages/profile-place.page.jsx, frontend/scripts/pages/tool.page.jsx
- Unmounts react components properly
**Merge after** #207
=> Feat: unmount react properly

app/controllers/api/v3/contexts_controller.rb, app/models/api/v3/context.rb, app/serializers/api/v3/contexts/context_serializer.rb, db/migrate/20180119094345_move_is_subnational_to_yellow_table.rb, db/schema_comments.yml, db/structure.sql
The flag belongs to context_properties.
=> Feature/move contexts.is_subnational to yellow table

frontend/package-lock.json, frontend/package.json, frontend/scripts/react-components/home/slider-section.component.jsx, frontend/styles/components/homepage/slider-section.scss
=> fix: adds media queries to react-siema instance

Gemfile, Gemfile.lock
Fixes the damn paperclip thing https://github.com/Vizzuality/trase/issues/253
=> Upgrade paperclip

frontend/scripts/components/tool/map-basemaps.component.js, frontend/scripts/containers/tool/map-basemaps.container.js
Fixes https://github.com/Vizzuality/trase/issues/216
=> Fix issue preventing selection of basemap

README.md, frontend/.env.sample, frontend/.eslintrc.json, frontend/config/webpack.config.js, frontend/package-lock.json, frontend/package.json, frontend/scripts/index.js
This PR includes new performance testing tools:
- Why Did You Update (piggybacks on React to console log when a component is rendering without need).
To enable the perf test a new env variable should be added: 
```sh
PERF_TEST=true
```
=> Feat: perf test

frontend/scripts/react-components/shared/hero.component.jsx
=> Fix highlighted story link

app/serializers/api/v3/contexts/recolor_by_attribute_serializer.rb, app/serializers/api/v3/contexts/resize_by_attribute_serializer.rb, doc/swagger.yaml, spec/support/schemas/v3_contexts.json
Include years available for recolor / resize in contexts endpoint
=> Added years of data avalable for recolor / resize

frontend/styles/components/explore/explore.scss
As in the title. That should conclude https://github.com/Vizzuality/trase/issues/277
=> Fix weird width transition on explore page

frontend/scripts/react-components/home/home.thunks.js
This resolves https://github.com/Vizzuality/trase/issues/354. Resetting tool state with extra parameters was broken.
=> Fix/home map page link takes us to sankey - issues with tool state reset

frontend/scripts/react-components/profiles/dropdown-tab-switcher.component.jsx, frontend/scripts/react-components/profiles/table.component.jsx, frontend/styles/components/profiles/area-table.scss, frontend/styles/components/profiles/dropdown-tab-switcher.scss, frontend/styles/components/profiles/scatterplot.scss
Placing tabs for scatterplot at the bottom of the chart as it was before.
=> place tabs for scatterplot at the bottom

app/controllers/api/v3/newsletter_subscriptions_controller.rb, spec/controllers/api/v3/newsletter_subscriptions_controller_spec.rb
Addresses https://appsignal.com/vizzuality/sites/5a8317dfe2954e5d54c8cf8c/incidents/5
=> Rescue Mailchimp::ListAlreadySubscribedError

frontend/scripts/components/tool/nodesTitles.component.js, frontend/scripts/reducers/app.reducer.js, frontend/styles/_settings.scss, frontend/styles/components/shared/veil.scss, frontend/styles/components/tool/map.scss, frontend/styles/layouts/l-tool.scss
=> Make tool page pills always visible

frontend/scripts/react-components/nav/filters-nav/recolor-by-selector/recolor-by-selector.component.jsx, frontend/scripts/react-components/nav/filters-nav/resize-by-selector/resize-by-selector.component.jsx
As the title says and the issue is [here](https://github.com/Vizzuality/trase/issues/473).
=> Show all options in resize-by selector and do not show "Selection" tooltip in recolor-by

frontend/scripts/react-components/tool/tool-search/tool-search-result.component.jsx, frontend/scripts/react-components/tool/tool-search/tool-search.component.jsx, frontend/scripts/react-components/tool/tool-search/tool-search.container.js
This PR fixes https://github.com/Vizzuality/trase/issues/484.
=> Fix sankey search on selecting item bug, add exporter/importer to supply chain text

frontend/styles/components/tool/map/map-context.scss, frontend/styles/components/tool/map/map-sidebar.scss
Resolving https://github.com/Vizzuality/trase/issues/118
=> Changing icon-layer-info color, not-allowed cursor for disable layers in sidebar menu

frontend/scripts/react-components/data-portal/data-portal-form.component.jsx, frontend/scripts/react-components/data-portal/data-portal-page.component.jsx, frontend/styles/components/data/custom-dataset.scss
This PR fixes the download form which didn't play nice with Transfix live translations feature.
=> Transifex form fix

frontend/scripts/components/tool/nodesTitles.component.js, frontend/scripts/react-components/nav/top-nav/global-search/global-search-result.component.jsx, frontend/scripts/react-components/tool/tool.reducer.js
This PR resolves https://github.com/Vizzuality/trase/issues/504
=> Fix selected columns for selected nodes

frontend/scripts/router/route-subscriber.js
This one fixes https://github.com/Vizzuality/trase/issues/512.
=> Fix redirect to profile page from profile place - remount the page

frontend/scripts/base/Container.js, frontend/scripts/components/tool/map-legend.component.jsx, frontend/scripts/pages/tool.page.jsx
Whenever we were going back and forth between the tool and any other page, the new map component was created but the old one still responded to any change in the store. That caused some weird issues like https://github.com/Vizzuality/trase/issues/516 and who knows what else.
=> Fix map issues caused by old component instances unsubscribed from store 

lib/modules/cache/warmer.rb
https://appsignal.com/vizzuality/sites/5ac78a01fc940e7ec5927d5b/incidents/5?timestamp=2018-07-02T15%3A18%3A53Z
=> Terminate cache warmer normally when Brazil - soy context not found

app/models/api/v3/node_property.rb, spec/models/api/v3/node_property_spec.rb
Fixes: https://appsignal.com/vizzuality/sites/5a7350b4b504f531d85ecf75/incidents/14?timestamp=2018-07-09T08%3A08%3A59Z
=> Validate one node property per node

Gemfile, Gemfile.lock, app/assets/javascripts/active_admin.js.coffee, app/assets/stylesheets/active_admin.scss, config/initializers/activeadmin_addons.rb
Just adds the gem and its default settings. For now, it seems to just add select2, which is cool enough. As we go, we can improve the integration
=> Add ActiveAdminAddons gem

frontend/scripts/actions/tool.actions.js, frontend/scripts/components/tool/tool-content.component.js, frontend/scripts/pages/tool.page.jsx, frontend/scripts/react-components/tool/tool.reducer.js, frontend/scripts/react-components/tool/tool.thunks.js, frontend/styles/layouts/l-tool.scss
https://www.pivotaltracker.com/story/show/160890383
=> Disable sankey/map animation while in loading state

frontend/scripts/react-components/dashboard-element/dashboard-element.actions.js, frontend/scripts/react-components/dashboard-element/dashboard-element.reducer.js, frontend/scripts/react-components/dashboard-element/dashboard-element.selectors.js, frontend/scripts/react-components/dashboard-element/dashboard-panel/companies-panel.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-panel/dashboard-panel.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-panel/sources-panel.component.jsx
Saves data for different tabs in order to always show selected item in dynamic sentence
=> Fix: show dynamic sentence selected items across tabs

frontend/scripts/react-components/dashboard-element/dashboard-element.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-element.container.jsx, frontend/styles/components/dashboard-element/dashboard-element.scss
Added header elements and functionality based on the designs.
###TEST###
- Verify the HTML and CSS
- Verify the functionality
=> add header elements and functionality based on the desgins

frontend/scripts/react-components/chart/styles.scss, frontend/scripts/react-components/dashboard-element/dashboard-element.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-element.reducer.js, frontend/scripts/react-components/dashboard-element/dashboard-element.selectors.js, frontend/scripts/react-components/dashboard-element/dashboard-panel/dashboard-panel.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-panel/sources-panel.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget-config.js, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget-legend.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.container.jsx, frontend/scripts/react-components/shared/tabs.component.jsx, frontend/styles/_base.scss, frontend/styles/components/dashboard-element/dashboard-widget-legend.scss, frontend/styles/components/dashboard-element/dashboard-widget.scss, frontend/styles/dashboard-element.scss
Adds the legend component and improves the dashboard widgets.
=> Feat: charts legend

frontend/scripts/react-components/chart/styles.scss, frontend/scripts/react-components/dashboard-element/dashboard-element.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-element.container.jsx, frontend/scripts/react-components/dashboard-element/dashboard-element.reducer.js, frontend/scripts/react-components/dashboard-element/dashboard-element.selectors.js, frontend/scripts/react-components/dashboard-element/dashboard-panel/dashboard-panel.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-panel/sources-panel.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget-config.js, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget-legend.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.container.jsx, frontend/scripts/react-components/shared/tabs.component.jsx, frontend/styles/_base.scss, frontend/styles/components/dashboard-element/dashboard-element.scss, frontend/styles/components/dashboard-element/dashboard-widget-legend.scss, frontend/styles/components/dashboard-element/dashboard-widget.scss, frontend/styles/dashboard-element.scss
Complete flow from options to indicators to charts.
This will probably have conflicts with #574
=> Feat: dashboard charts

frontend/scripts/react-components/dashboard-element/dashboard-element.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-element.container.jsx, frontend/scripts/react-components/dashboard-element/dashboard-element.selectors.js, frontend/styles/components/dashboard-element/dashboard-element.scss
Adds the dynamic sentence text to the dashboard header.
=> Feat: display dynamic sentence on dashboard header

app/admin/api/v3/dashboard_template.rb, app/controllers/api/v3/dashboards/templates_controller.rb, app/models/api/v3/commodity.rb, app/models/api/v3/country.rb, app/models/api/v3/dashboard_template.rb, app/serializers/api/v3/dashboards/template_serializer.rb, db/migrate/20181017053240_add_category_to_dashboard_template.rb, db/structure.sql, frontend/scripts/react-components/dashboard-root/dashboard-root.actions.js, frontend/scripts/react-components/dashboard-root/dashboard-root.component.jsx, frontend/scripts/react-components/dashboard-root/dashboard-root.container.js, frontend/scripts/react-components/dashboard-root/dashboard-root.reducer.js, frontend/scripts/react-components/dashboard-root/dashboard-root.thunks.js, frontend/scripts/router/router.js, frontend/scripts/store.js, frontend/scripts/utils/getURLFromParams.js, frontend/styles/components/dashboard-root/dashboard-root.scss, frontend/styles/dashboard-root.scss, spec/support/schemas/dashboards_templates.json
Missing (for other PRs)
- create the actual links to the dashboards
- links to indicators
=> Load dashboard templates as frontend cards

frontend/scripts/react-components/dashboard-element/dashboard-element.actions.js, frontend/scripts/react-components/dashboard-element/dashboard-element.reducer.js, frontend/scripts/react-components/dashboard-element/dashboard-element.saga.js, frontend/scripts/react-components/dashboard-element/dashboard-panel/commodities-panel.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-panel/companies-panel.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-panel/dashboard-panel.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-panel/dashboard-panel.container.jsx, frontend/scripts/react-components/dashboard-element/dashboard-panel/destinations-panel.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-panel/sources-panel.component.jsx, frontend/scripts/react-components/shared/search-input/search-input.component.jsx, frontend/scripts/utils/getURLFromParams.js
This PR connects all panels to the dashboard search. Also fixes a BIG 🐛 when adding data that depends on a tab.
=> Feat: dashboard panel search

app/services/api/v3/dashboards/retrieve_attributes.rb
Fixes unavailable indicators which are actually available 🤦‍♀️
=> This what happens when you get your booleans the other way round

frontend/scripts/pages/dashboard-element.page.jsx, frontend/scripts/pages/dashboard-root.page.jsx
This PR adds missing unmount for the Nav and the Footer in the dashboard pages, this also fixes a BIG crash from the side of React.
=> fix: unmount dashboard pages nv/footer on route change

app/services/api/v3/dashboards/chart_data_from_flow_attributes.rb, app/services/api/v3/dashboards/chart_data_from_node_attributes.rb, frontend/scripts/react-components/dashboard-element/dashboard-element.reducer.js, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget-config.js, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget-legend.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget-tooltip.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.container.jsx, frontend/scripts/react-components/widgets/widget.component.jsx, frontend/scripts/react-components/widgets/widgets.actions.js, frontend/scripts/react-components/widgets/widgets.reducer.js, frontend/styles/_settings.scss, frontend/styles/components/dashboard-element/dashboard-widget-legend.scss
This PR connects charts to real data.
=> Feat: adds some real data to dashboard charts

frontend/html/statics/icons.svg, frontend/scripts/react-components/dashboard-element/dashboard-element.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.container.jsx, frontend/scripts/react-components/shared/ErrorCatch.jsx, frontend/styles/components/dashboard-element/dashboard-element.scss, frontend/styles/components/dashboard-element/dashboard-widget.scss
This PR adds the missing share and download icons. Also includes a Error Boundary component to catch runtime errors in the widgets.
=> Fix: adds links icons in dashboard

frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget-config.js
Hides tooltip cursor in barcharts
=> Fix: hide cursor on barcharts

frontend/scripts/react-components/chart/component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget-config.js, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget-tooltip.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.container.jsx
This PR makes pie charts work again, now with real data, even if the data makes no sense 😅 .
=> fix: adds compatibility for dynamic configs with pie chart

frontend/scripts/react-components/dashboard-element/dashboard-element.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-element.container.jsx, frontend/scripts/react-components/dashboard-element/dashboard-element.selectors.js, frontend/scripts/react-components/dashboard-element/dashboard-indicators/dashboard-indicators.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-panel/dashboard-panel.container.jsx, frontend/scripts/react-components/dashboard-element/dashboard-welcome.component.jsx, frontend/scripts/react-components/dashboard-root/dashboard-root.component.jsx, frontend/styles/components/dashboard-element/dashboard-panel.scss, frontend/styles/components/dashboard-element/dashboard-welcome.scss
This PR updates texts in dashboards + fixes some styles in the welcome modal.
=> Chore: change texts

app/models/api/v3/readonly/dashboards/node_attribute.rb, config/deploy.rb
* ensure dashboards_node_attributes_mv is not refreshed concurrently
* ensure sidekiq is restarted and loads current version of code
=> Fixes to data update process

frontend/scripts/react-components/nav/top-nav/top-nav.component.jsx, frontend/styles/_helpers.scss, frontend/styles/components/shared/top-nav.scss
[Change breakpoint for header menu to acommodate yearbook](https://www.pivotaltracker.com/story/show/159590942)
=> fix navbar media queries

frontend/scripts/pages/profile-node.page.jsx, frontend/scripts/react-components/profiles/actor-summary.component.jsx, frontend/scripts/react-components/profiles/line-legend.component.jsx, frontend/scripts/react-components/profiles/mini-sankey.component.jsx, frontend/scripts/react-components/profiles/place-summary.component.jsx
[Years reverse order in drop down when flicking between profiles and sankey/map view](https://www.pivotaltracker.com/story/show/161919337)
=> Fix: sort mutates stuff too

frontend/package.json, frontend/scripts/react-components/profiles/line.component.jsx, frontend/scripts/react-components/profiles/scatterplot.component.jsx
[Top sourcing regions graph on company profiles appears broken](https://www.pivotaltracker.com/story/show/161918151)
=> fix: line chart add support for discontinuos data

frontend/styles/layouts/l-profile-actor.scss
[Profile refactor - Tooltips showing outside of canvas](https://www.pivotaltracker.com/story/show/159590920)
=> fixes table tooltip and linechart padding

frontend/scripts/constants.js, frontend/scripts/react-components/explore/explore.actions.js, frontend/scripts/react-components/explore/explore.component.jsx, frontend/scripts/react-components/explore/explore.container.js, frontend/scripts/react-components/explore/explore.reducer.js, frontend/scripts/react-components/explore/top.component.jsx, frontend/scripts/react-components/profiles/dropdown-tab-switcher.component.jsx, frontend/scripts/react-components/profiles/line.component.jsx, frontend/styles/components/explore/explore.scss
This PR handles an edge case where no companies data is available because all data is `unknown`.
=> Feat: add fallback text

frontend/scripts/react-components/nav/filters-nav/recolor-by-selector/recolor-by-selector.component.jsx, frontend/scripts/react-components/nav/filters-nav/resize-by-selector/resize-by-selector.component.jsx
This PR addresses some issues with the ordering of the `recolorBy` selector. Complexity and order of such component were crazy, so lots of changes. Test Test Test. 🙏
=> Fix: refactor recolorBy selector

app/services/api/v3/actors/exporting_companies_plot.rb
https://www.pivotaltracker.com/story/show/161919120
=> Renamed LAND_USE to SOY_AREA_

frontend/package-lock.json, frontend/package.json, frontend/scripts/react-components/tool/tool-search/tool-search-result.component.jsx, frontend/scripts/react-components/tool/tool-search/tool-search.component.jsx, frontend/scripts/react-components/tool/tool-search/tool-search.container.js
Fixes navigation towards profile pages from the sankey search results.
=> fix sankey search link to profiles

frontend/package-lock.json, frontend/package.json, frontend/scripts/actions/tool.actions.js, frontend/scripts/components/tool/map.component.js, frontend/scripts/pages/tool.page.jsx, frontend/scripts/react-components/shared/app.thunks.js, frontend/scripts/react-components/tool/tool.reducer.js, frontend/scripts/react-components/tool/tool.thunks.js, package-lock.json, package.json
This PR improves the way we fetch the vector maps and tackles a racing condition where opening the map in a context different that the default could hang forever loading.
=> Fix: vector maps fetching

app/admin/api/v3/database_export.rb, app/services/api/v3/s3_object_list.rb, app/views/admin/database_export/_form.html.erb
=> Merry christmas

frontend/scripts/react-components/profile-node/profile-node-widgets/gfw-widget.component.jsx
The idea is to only have the GLAD GFW widget.
=> fix: removes the gfw deforestation widget

frontend/scripts/pages/explore.page.jsx, frontend/scripts/react-components/data-portal/filter-tooltip/filter-tooltip.component.jsx, frontend/scripts/react-components/explore/explore.component.jsx, frontend/scripts/react-components/explore/explore.container.js, frontend/scripts/react-components/explore/explore.scss, frontend/scripts/react-components/explore/explore.thunks.js, frontend/scripts/react-components/home/home.component.jsx, frontend/scripts/react-components/home/homepage.scss, frontend/scripts/react-components/home/sentence-selector/sentence-selector.component.jsx, frontend/scripts/react-components/home/sentence-selector/sentence-selector.container.js, frontend/scripts/react-components/home/sentence-selector/sentence-selector.scss, frontend/scripts/react-components/nav/filters-nav/filters-nav.component.jsx, frontend/scripts/react-components/nav/filters-nav/filters-nav.selectors.js, frontend/scripts/react-components/nav/top-nav/top-nav.component.jsx, frontend/scripts/react-components/nav/top-nav/top-nav.container.js, frontend/scripts/react-components/shared/dropdown.component.jsx, frontend/scripts/react-components/shared/sentence-selector/sentence-selector.component.jsx, frontend/scripts/react-components/shared/sentence-selector/sentence-selector.container.js, frontend/scripts/react-components/shared/sentence-selector/sentence-selector.scss, frontend/scripts/react-components/shared/world-map/world-map.component.jsx, frontend/scripts/react-components/shared/world-map/world-map.container.js, frontend/scripts/react-components/shared/world-map/world-map.selectors.js, frontend/scripts/router/router.js, frontend/scripts/utils/stateURL.js, frontend/styles/components/tool/years-selector.scss
This PR update the world map component, removes the filter nav from explore and uses the sentence selector instead.
=> Feat: explore page refactor

frontend/scripts/react-components/shared/tabs/tabs.component.jsx, frontend/scripts/react-components/shared/tabs/tabs.scss
Try http://localhost:8081/dashboards -> regions -> indonesia
=> Fix styling of tabs component when there is only one tab

app/models/api/v3/ind_commodity_property.rb, app/models/api/v3/ind_context_property.rb, app/models/api/v3/ind_country_property.rb, app/models/api/v3/qual_commodity_property.rb, app/models/api/v3/qual_context_property.rb, app/models/api/v3/qual_country_property.rb, app/models/api/v3/quant_commodity_property.rb, app/models/api/v3/quant_context_property.rb, app/models/api/v3/quant_country_property.rb
Add refresh methods to tooltip-related models to refresh materialized views.
PT task: https://www.pivotaltracker.com/n/projects/1637931/stories/163422263
=> Add cms support for new tables

frontend/scripts/actions/tool.actions.js
This PR fixes an issue in the Sankey, that lost the choropleth when changing column and didn't restored it afterwards.
Fixes: https://www.pivotaltracker.com/story/show/164458131
=> Fix: make sure to enable choro on column change

frontend/scripts/react-components/shared/steps-tracker/steps-tracker.component.jsx, frontend/scripts/react-components/shared/steps-tracker/steps-tracker.scss
=> Refactor step tracker

app/controllers/api/v3/dashboards/charts/multi_year_no_ncont_node_type_view_controller.rb, app/services/api/v3/dashboards/charts/multi_year_no_ncont_node_type_view.rb, app/services/concerns/api/v3/dashboards/charts/helpers.rb, doc/swagger.yaml, spec/responses/api/v3/dashboards/charts/multi_year_no_ncont_node_type_view_spec.rb, spec/services/api/v3/dashboards/charts/multi_year_no_ncont_node_type_view_spec.rb, spec/support/schemas/dashboards_charts_multi_year_no_ncont_node_type_view.json
http://localhost:3000/api/v3/dashboards/charts/multi_year_no_ncont_node_type_view?node_type_id=1&country_id=27&commodity_id=1&cont_attribute_id=1&start_year=2015&end_year=2016&top_n=3
```
{
"data":[
{
"y2":12652260.6013067,
"y0":39395678.071226,
"y3":16353132.1404154,
"y1":29063865.178816,
"x":2015
},
{
"y1":29212256.0995169,
"y3":17523965.5924515,
"y0":37220927.4416087,
"y2":12339564.8549034,
"x":2016
}
],
"meta":{
"xAxis":{
"type":"category",
"label":"Year",
"prefix":"",
"format":"",
"suffix":""
},
"yAxis":{
"type":"number",
"label":"Trade volume",
"prefix":"",
"format":"",
"suffix":"t"
},
"x":{
"label":"Year",
"tooltip":{
"prefix":"",
"format":"",
"suffix":""
}
},
"y0":{
"label":"CERRADO",
"tooltip":{
"prefix":"",
"format":"",
"suffix":""
}
},
"y1":{
"label":"MATA ATLANTICA", …
```
=> Multi year, no ncont, node type view (stacked bar chart)

frontend/public/images/dashboards/pattern.svg, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.scss
=> Change no data widget appearance

frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.selectors.js
This PR checks that the data keys are actually data keys.
=> Fix: makes meta data keys validation stronger

app/models/api/v3/context.rb, app/serializers/api/v3/contexts/context_serializer.rb, spec/models/api/v3/context_spec.rb, spec/services/api/v3/nodes_search/filter_spec.rb, spec/support/contexts/api/v3/paraguay/paraguay_context_node_types.rb, spec/support/contexts/api/v3/paraguay/paraguay_flows.rb, spec/support/contexts/api/v3/paraguay/paraguay_soy_nodes.rb
https://www.pivotaltracker.com/story/show/165055602
=> Fix for mixed up biomes in sankey filter dropdown

frontend/public/tooltips.json, frontend/scripts/react-components/logistics-map/logistics-map-legend/logistics-map-legend.component.jsx, frontend/scripts/react-components/shared/help-tooltip/help-tooltip.scss
Fixed tooltips and added texts for Beef. Soy text are still missing
=> Update label text and fix label style

frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.container.jsx
- Use a selector
- Change text to 'Selection overview'
=> Change global for selection

frontend/config/webpack.config.dev.js, frontend/config/webpack.config.js, frontend/config/webpack.config.prod.js, frontend/config/webpack.config.staging.js, frontend/html/base.ejs, frontend/html/includes/_head.ejs, frontend/html/tool.ejs, frontend/scripts/react-components/shared/dropdown/dropdown.component.jsx, frontend/styles/_base.scss
uses css-mini-extract on production
=> fix styles loading

app/services/api/v3/dashboards/charts/multi_year_no_ncont_node_type_view.rb, app/services/api/v3/dashboards/charts/single_year_ncont_node_type_view.rb, app/services/api/v3/dashboards/charts/single_year_no_ncont_node_type_view.rb, app/services/concerns/api/v3/dashboards/charts/helpers.rb, spec/services/api/v3/dashboards/charts/multi_year_no_ncont_node_type_view_spec.rb, spec/services/api/v3/dashboards/charts/single_year_no_ncont_node_type_view_spec.rb
https://www.pivotaltracker.com/story/show/165244800
=> Removed unknown nodes from top n nodes in charts

frontend/scripts/react-components/profile-node/profile-node-widgets/top-consumers-widget.component.jsx
- Disabled link. I Used null to avoid prop warnings
=> Don't use link in the importer countries the sankey

app/services/api/v3/actors/basic_attributes.rb
Fixes regression in actor basic attributes
=> Suppress blank zero deforestation or forest 500

frontend/scripts/react-components/profiles/top-destinations-chart.component.jsx
=> Node name was not shown

frontend/scripts/actions/tool.actions.js, frontend/scripts/reducers/helpers/getChoropleth.js
Checks that the selected geo column has choropleth enabled before setting it.
=> Prevents setting choropleth on columns that dont have it

frontend/scripts/react-components/nav/locale-selector/locale-selector.component.jsx, frontend/scripts/router/router.js
This PR fixes transifex default lang, causing mismatches with app lang and selector lang.
=> Fix transifex default lang

frontend/scripts/actions/app.actions.js, frontend/scripts/index.ejs, frontend/scripts/index.js, frontend/scripts/react-components/dashboard-element/dashboard-panel/dashboard-panel.component.jsx, frontend/scripts/react-components/nav/locale-selector/locale-selector.component.jsx, frontend/scripts/react-components/nav/locale-selector/locale-selector.container.js, frontend/scripts/react-components/profiles/button-links/button-links.component.jsx, frontend/scripts/react-components/profiles/profile-title.component.jsx, frontend/scripts/react-components/shared/hero/hero.component.jsx, frontend/scripts/react-components/shared/hero/hero.scss, frontend/scripts/react-components/shared/img/img-background.component.jsx, frontend/scripts/react-components/shared/img/img.component.jsx, frontend/scripts/react-components/shared/sentence-selector/sentence-selector.component.jsx, frontend/scripts/react-components/shared/tags-group/tag/tag.component.jsx, frontend/scripts/react-components/shared/tags-group/tags-group.component.jsx, frontend/scripts/reducers/app.reducer.js, frontend/scripts/router/router.js, frontend/yarn.lock
Locale selector wasn't working properly sometimes, this PR turns it around. We rely on Transifex loading first to add the languages to the store later.
=> Fix: change locale selector

lib/tasks/downloads.rake
Not sure how we went on so long with this bug in place 🤦‍♀
=> Fixed rake task name

frontend/scripts/index.ejs
=> defer transifex script

app/models/api/v3/readonly/node.rb, app/serializers/api/v3/nodes_search/node_serializer.rb, app/services/api/v3/nodes_search/filter.rb, db/migrate/20190624114103_add_years_to_nodes_mv.rb, db/structure.sql, db/views/nodes_mv_v07.sql, doc/swagger.yaml, spec/support/schemas/v3_nodes_search.json
Requires `bundle exec rake db:migrate`
`http://localhost:3000/api/v3/nodes/search?query=yeo&context_id=1`
```
{
"data":[
{
"id":25742,
"mainId":87851,
"name":"YEO HIAP SENG",
"nodeType":"IMPORTER",
"contextId":1,
"profile":"actor",
"isSubnational":true,
"years":[
2013,
2014
]
}
]
}
```
=> Added years to global nodes search response

frontend/scripts/react-components/shared/units-tooltip/units-tooltip.component.jsx
This PR fixes the crash on some pages due to infinite update loop using Units Tooltip.
=> updates units-tooltip to use react hooks

frontend/scripts/index.js, frontend/scripts/react-components/tool-layers/tool-layers.initial-state.js, frontend/scripts/react-components/tool-layers/tool-layers.reducer.js, frontend/scripts/react-components/tool-layers/tool-layers.selectors.js, frontend/scripts/react-components/tool-layers/tool-layers.serializers.js, frontend/scripts/react-components/tool-links/tool-links.reducer.js, frontend/scripts/react-components/tool-links/tool-links.saga.js, frontend/scripts/react-components/tool/map-dimensions/map-dimensions.component.js, frontend/scripts/react-components/tool/map-dimensions/map-dimensions.container.js, frontend/scripts/react-components/tool/map/map.component.js, frontend/scripts/react-components/tool/map/map.container.js, frontend/scripts/react-components/tool/tool.actions.js, frontend/scripts/react-components/tool/tool.component.jsx, frontend/scripts/react-components/tool/tool.js
This PR adds the corresponding logic needed to save the map state in the url. Until this day the map state was never been saved in the url. Small step for url bars, big step for trase flows page 👨‍🚀 .
=> Feat: serialize map state

frontend/scripts/analytics/tool.events.js, frontend/scripts/index.js, frontend/scripts/react-components/nav/filters-nav/filters-nav.container.js, frontend/scripts/react-components/nav/filters-nav/filters-nav.selectors.js, frontend/scripts/react-components/nav/filters-nav/recolor-by-selector/recolor-by-selector.js, frontend/scripts/react-components/nav/filters-nav/recolor-by-selector/recolor-by-selector.selectors.js, frontend/scripts/react-components/tool-layers/tool-layers.serializers.js, frontend/scripts/react-components/tool-links/tool-links.actions.js, frontend/scripts/react-components/tool-links/tool-links.fetch.saga.js, frontend/scripts/react-components/tool-links/tool-links.initial-state.js, frontend/scripts/react-components/tool-links/tool-links.reducer.js, frontend/scripts/react-components/tool-links/tool-links.saga.js, frontend/scripts/react-components/tool-links/tool-links.selectors.js, frontend/scripts/react-components/tool-links/tool-links.serializers.js, frontend/scripts/react-components/tool/map-context/map-context.component.jsx, frontend/scripts/react-components/tool/map/map.container.js, frontend/scripts/react-components/tool/nodes-titles/nodes-titles.container.js, frontend/scripts/react-components/tool/sankey/sankey.container.js, frontend/scripts/react-components/tool/tool-content/tool-content.component.js, frontend/scripts/react-components/tool/tool-content/tool-content.container.js, frontend/scripts/react-components/tool/tool.actions.js, frontend/scripts/react-components/tool/tool.js, frontend/scripts/react-components/tool/tool.selectors.js, frontend/scripts/reducers/app.reducer.js, frontend/scripts/selectors/indicators.selectors.js
This PR adds missing filters in the sankey to the url.
=> Feat: refactor sankey filters

app/admin/api/v3/top_profile.rb
Clear cache after changes for top profiles on _update_, _create_ and _destroy_
=> Clear cache after changes for top profiles

app/controllers/api/v3/profile_metadata_controller.rb, app/models/api/v3/node.rb, app/serializers/api/v3/profile_metadata/available_years_serializer.rb, spec/responses/api/v3/nodes/profile_metadata_spec.rb
Add list of available years for node in profile metadata endpoint.
=> Add list of available years for node in profile metadata endpoint

.travis.yml, frontend/.eslintrc.json, frontend/config/webpack.config.dev.js, frontend/config/webpack.config.js, frontend/config/webpack.config.prod.js, frontend/config/webpack.config.staging.js, frontend/docs/index.mdx, frontend/env.test.js, frontend/jest.config.js, frontend/scripts/react-components/profile-node/profile-node.component.jsx, frontend/scripts/react-components/profile-node/profile-node.container.jsx, frontend/scripts/react-components/profiles/profile-title.component.jsx, frontend/scripts/react-components/shared/in-view.component.jsx, frontend/scripts/react-components/widgets/widget.component.jsx, frontend/scripts/react-components/widgets/widgets.actions.js, frontend/scripts/react-components/widgets/widgets.reducer.js, frontend/scripts/tests/widgets/actions.test.js, frontend/scripts/utils/saga-utils.js
This PR fixes the `<Widget />` component and actions to cancel pending requests when a new one is triggered. Also makes sure to remount the profile page charts when navigating from one into another.
=> Fix: profiles page not loading

app/admin/api/v3/top_profile.rb, app/models/api/v3/top_profile.rb, spec/controllers/admin/top_profiles_controller_spec.rb, spec/responses/api/v3/top_profiles_spec.rb
PT task: https://www.pivotaltracker.com/story/show/167222198
- Add validation for context and node presence in top profile
- Move `before_create` callback to top profile model
- Adjust specs
=> Add validation for context and node presence in top profile

frontend/scripts/react-components/logistics-map/logistics-map-layers.js, frontend/scripts/react-components/logistics-map/logistics-map.actions.js
Change the dataset for brazil:
Before:
After:
=> Use brazil_storage_facilities instead of the sample dataset

app/serializers/api/v3/top_profiles_serializer.rb, app/services/api/v3/top_profiles/get_matching_image.rb
Return large top profile images to FE instead of originals as per request of @sorodrigo.
=> Return large top profile images instead of originals

frontend/scripts/react-components/dashboard-element/dashboard-element.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-element.container.jsx, frontend/scripts/react-components/dashboard-element/dashboard-element.fetch.saga.js, frontend/scripts/react-components/dashboard-element/dashboard-element.reducer.js, frontend/scripts/react-components/dashboard-element/dashboard-element.selectors.js, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget-fetch.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.container.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.selectors.js, frontend/scripts/react-components/shared/grid-list-item/grid-list-item.component.jsx, frontend/scripts/tests/dashboard-element/reducer.test.js, frontend/scripts/tests/puppeteer/__recordings__/dashboard_3837856731/recording.har, frontend/scripts/tests/puppeteer/__recordings__/profile-actor_1717795718/recording.har, frontend/scripts/tests/puppeteer/dashboards.test.e2e.js
Adds support for groupings in dashboard widgets, this allows backend to specify grouping of charts that will be shown using a dropdown.
=> Feat: chart widget groupings

app/admin/api/v3/top_profile.rb, app/models/api/v3/top_profile_image.rb, app/serializers/api/v3/top_profiles_serializer.rb
I know this looks weird, but it is effectively the same "design pattern" as in https://github.com/Vizzuality/trase/blob/develop/app/serializers/content/post_serializer.rb and it makes it work on staging ¯\_(ツ)_/¯
=> fix for top profile images

app/admin/api/v3/top_profile_image.rb
https://www.pivotaltracker.com/story/show/167162426
=> Added image_url on admin top profile images

app/services/api/v3/download/flow_download_pivot_query.rb
=> Revert "Add new column to download to ensure unique rows"

frontend/docs/backend/onboarding.mdx
This is the beginning of backend onboarding documentation, based on what we covered with Jesús so far.
Here are some comments from Marta explaining the need of such documentation: https://github.com/Vizzuality/trase/issues/717
I think it would be great if Jesús would add either information or questions here as he's now discovering Trase, then hopefully the next person who starts will have an easier job 🌻
=> Onboarding documentation start

frontend/scripts/react-components/nav/filters-nav/nav-dropdown-selector/nav-dropdown-selector.component.jsx, frontend/scripts/react-components/shared/dropdown/dropdown-button.component.jsx, frontend/scripts/react-components/shared/dropdown/dropdown-content.component.jsx, frontend/scripts/react-components/shared/dropdown/dropdown-item.component.jsx, frontend/scripts/react-components/shared/dropdown/dropdown.component.jsx
This PR reorganizes the dropdown to include useMemo optimization and splits it into more manageable components.
=> Re-organize dropdown component

frontend/scripts/react-components/dashboard-element/dashboard-element.fetch.saga.js, frontend/scripts/react-components/shared/profile-selector/profile-panel/profile-panel.fetch.saga.js, frontend/scripts/react-components/tool-layers/tool-layers.fetch.saga.js, frontend/scripts/react-components/tool-links/tool-links.fetch.saga.js, frontend/scripts/react-components/tool/sankey/sort-flows.js, frontend/scripts/react-components/widgets/widgets.actions.js, frontend/scripts/reducers/helpers/getNodeMeta.js, frontend/scripts/utils/createReducer.js
The app crashed when highlighting in the map. Please, let me know if this is enough
=> Bug: Territorial deforestation crash

frontend/package.json, frontend/scripts/react-components/explore/explore.selectors.js, frontend/scripts/react-components/explore/top-cards/top-cards.component.jsx, frontend/scripts/react-components/explore/top-cards/top-cards.scss, frontend/yarn.lock
- Improve cards positioning for different screens (not mobile)
- Animate cards enter with react spring
=> Improve cards positioning and animate

app/services/api/v3/places/basic_attributes.rb
https://www.pivotaltracker.com/story/show/168238578
=> Return pasture_area where available

frontend/styles/_settings.scss
=> adds new context zdc classes

frontend/scripts/react-components/explore/explore.actions.js, frontend/scripts/react-components/explore/explore.component.jsx, frontend/scripts/react-components/explore/tool-links-modal/tool-links-modal.component.jsx, frontend/scripts/react-components/explore/tool-links-modal/tool-links-modal.js, frontend/scripts/react-components/explore/tool-links-modal/tool-links-modal.scss, frontend/scripts/react-components/explore/top-cards/top-cards.component.jsx
- Create tool links modal UI
- Update links to data view and Sankey
Missing: 
- We need the backend changes ready to be able to pass the exact links to each part of the app
- Background images of the links to be determined
=> Create tool-links-modal and update links

app/controllers/api/v3/columns_controller.rb, app/serializers/api/v3/columns/column_serializer.rb, frontend/docs/swagger.yaml, spec/controllers/api/v3/dashboards/companies_controller_spec.rb, spec/controllers/api/v3/dashboards/sources_controller_spec.rb, spec/services/api/v3/dashboards/parametrised_charts/flow_values_spec.rb, spec/support/contexts/api/v3/brazil/brazil_context_node_types.rb, spec/support/contexts/api/v3/brazil/brazil_soy_nodes.rb, spec/support/schemas/v3_columns.json
https://www.pivotaltracker.com/story/show/168505854
=> Added role to columns endpoint

app/admin/api/v3/context_node_type_property.rb, app/models/api/v3/context_node_type_property.rb, db/migrate/20190924075531_make_role_and_prefix_mandatory.rb, db/structure.sql, spec/factories/api/v3/api_v3_context_node_type_properties.rb, spec/models/api/v3/context_node_type_property_spec.rb
https://www.pivotaltracker.com/story/show/168630532
=> Make role and prefix mandatory in context_node_type_properties

frontend/scripts/analytics/home.events.js, frontend/scripts/react-components/home/entrypoints/entrypoints.component.jsx, frontend/scripts/react-components/home/entrypoints/entrypoints.scss, frontend/scripts/react-components/home/home.actions.js, frontend/scripts/react-components/home/home.component.jsx, frontend/scripts/react-components/home/home.container.js, frontend/scripts/react-components/home/homepage.scss, frontend/scripts/react-components/shared/units-tooltip/units-tooltip.scss, frontend/styles/_settings.scss
This PR reverts the homepage insights section.
=> Hotfix: revert home insights

frontend/scripts/react-components/tool/splitted-view/splitted-view.component.jsx
Remove feature flag on the Splitted view. This change was also made as a hotfix to master branch
=> Remove feature flag on the Splitted view

app/controllers/api/public/nodes/exporters_controller.rb, app/controllers/api/public/nodes/importers_controller.rb, app/services/api/public/nodes/exporters/filter.rb, app/services/api/public/nodes/importers/filter.rb, config/routes.rb, spec/responses/api/public/nodes_exporters_spec.rb, spec/responses/api/public/nodes_importers_spec.rb, spec/services/api/public/nodes/exporters_filter_spec.rb, spec/services/api/public/nodes/importers_filter_spec.rb
https://www.pivotaltracker.com/story/show/167803998
=> Public API exporters and importers endpoints

frontend/scripts/react-components/legacy-explore/explore.component.jsx, frontend/scripts/react-components/legacy-explore/explore.scss
- Recover map on explore
- Fix map cut on big screens
=> Fix map not showing on explore

frontend/scripts/analytics/explore.events.js, frontend/scripts/react-components/explore/explore.actions.js
Add destination of the modal (Sankey/dashboards) to the card link event
=> Just add destination to the event

app/controllers/api/public/node_types_controller.rb, app/serializers/api/public/node_types/node_type_serializer.rb, app/serializers/api/public/node_types/path_node_types_serializer.rb, app/services/api/public/node_types/filter.rb, config/routes.rb, spec/responses/api/public/node_types_spec.rb, spec/support/schemas/public_node_types.json
https://www.pivotaltracker.com/story/show/169391898
https://public-api-trase-v1.docs.stoplight.io/reference/node-types/getnodetypes
=> Node types endpoint

frontend/scripts/react-components/tool/sankey/sankey.selectors.js, frontend/scripts/reducers/helpers/splitVisibleNodesByColumn.js
This fixes a crash of the extra column only on ff
=> Correct column position in split

frontend/scripts/react-components/nodes-panel/nodes-panel.reducer.js, frontend/scripts/react-components/nodes-panel/nodes-panel.selectors.js
This PR makes sure subsequent panels data is cleared on changes, fixes tab panel data filtering.
=> fix: panel filtering after rehydration

frontend/scripts/react-components/logistics-map/logistics-map-download/logistics-map-download.component.jsx, frontend/scripts/react-components/logistics-map/logistics-map-download/logistics-map-download.scss, frontend/scripts/react-components/logistics-map/logistics-map-layers.js, frontend/scripts/react-components/logistics-map/logistics-map.container.jsx, frontend/scripts/react-components/logistics-map/logistics-map.selectors.js, frontend/scripts/react-components/nav/filters-nav/filters-nav.selectors.js, frontend/scripts/tests/dashboard-element/fetch.saga.test.js, frontend/scripts/tests/dashboard-element/reducer.test.js, frontend/scripts/tests/dashboard-element/saga.test.js, frontend/scripts/tests/dashboard-element/table-modal/table-modal-selectors.test.js, frontend/scripts/tests/dashboard-widget/dashboard-widget-selectors.test.js
https://www.pivotaltracker.com/story/show/169599722
=> Feat: update logistics map

frontend/scripts/react-components/dashboard-element/dashboard-element.fetch.saga.js, frontend/scripts/react-components/dashboard-element/dashboard-element.selectors.js, frontend/scripts/react-components/explore/explore.component.jsx, frontend/scripts/react-components/nodes-panel/destinations-panel/destinations-panel.component.jsx, frontend/scripts/react-components/nodes-panel/destinations-panel/destinations-panel.js, frontend/scripts/react-components/nodes-panel/exporters-panel/exporters-panel.component.jsx, frontend/scripts/react-components/nodes-panel/exporters-panel/exporters-panel.js, frontend/scripts/react-components/nodes-panel/importers-panel/importers-panel.component.jsx, frontend/scripts/react-components/nodes-panel/importers-panel/importers-panel.js, frontend/scripts/react-components/nodes-panel/nodes-panel.actions.js, frontend/scripts/react-components/nodes-panel/nodes-panel.fetch.saga.js, frontend/scripts/react-components/nodes-panel/nodes-panel.initial-state.js, frontend/scripts/react-components/nodes-panel/nodes-panel.reducer.js, frontend/scripts/react-components/nodes-panel/nodes-panel.selectors.js, frontend/scripts/react-components/nodes-panel/nodes-panel.serializers.js, frontend/scripts/react-components/nodes-panel/sources-panel/sources-panel.component.jsx, frontend/scripts/react-components/nodes-panel/sources-panel/sources-panel.js, frontend/scripts/react-components/shared/grid-list-item/grid-list-item.component.jsx, frontend/scripts/react-components/shared/grid-list-item/grid-list-item.scss, frontend/scripts/react-components/shared/grid-list/grid-list.component.jsx, frontend/scripts/react-components/tool/tool-modal/base-modal/base-modal.component.jsx
Adds select all to dashboard.
**TODO:**
- Add excluded nodes ids param to flow endpoint once the panel controls it.
=> Feat: select all panel

frontend/scripts/react-components/nav/filters-nav/context-modal-button/context-modal-button.component.jsx, frontend/scripts/react-components/nav/filters-nav/context-modal-button/context-modal-button.scss, frontend/scripts/react-components/nodes-panel/destinations-panel/destinations-panel.component.jsx, frontend/scripts/react-components/nodes-panel/destinations-panel/destinations-panel.js, frontend/scripts/react-components/nodes-panel/destinations-panel/destinations-panel.scss, frontend/scripts/react-components/nodes-panel/exporters-panel/exporters-panel.component.jsx, frontend/scripts/react-components/nodes-panel/exporters-panel/exporters-panel.js, frontend/scripts/react-components/nodes-panel/importers-panel/importers-panel.component.jsx, frontend/scripts/react-components/nodes-panel/importers-panel/importers-panel.js, frontend/scripts/react-components/nodes-panel/nodes-panel.actions.js, frontend/scripts/react-components/nodes-panel/nodes-panel.fetch.saga.js, frontend/scripts/react-components/nodes-panel/nodes-panel.initial-state.js, frontend/scripts/react-components/nodes-panel/nodes-panel.reducer.js, frontend/scripts/react-components/nodes-panel/nodes-panel.saga.js, frontend/scripts/react-components/nodes-panel/nodes-panel.selectors.js, frontend/scripts/react-components/nodes-panel/order-by.component.jsx, frontend/scripts/react-components/shared/dropdown/dropdown-panel.variant.scss, frontend/scripts/react-components/shared/grid-list-item/grid-list-item.component.jsx, frontend/scripts/tests/puppeteer/__recordings__/dashboard_3837856731/recording.har, frontend/scripts/tests/puppeteer/dashboards.test.e2e.js
Adds order by to `destinations`, `exporters` and `importers` panels.
=> Feat: order by

frontend/scripts/react-components/dashboard-element/dashboard-element.saga.js, frontend/scripts/react-components/nodes-panel/commodities-panel/commodities-panel.component.jsx, frontend/scripts/react-components/nodes-panel/destinations-panel/destinations-panel.component.jsx, frontend/scripts/react-components/nodes-panel/exporters-panel/exporters-panel.component.jsx, frontend/scripts/react-components/nodes-panel/importers-panel/importers-panel.component.jsx, frontend/scripts/react-components/nodes-panel/nodes-panel.actions.js, frontend/scripts/react-components/nodes-panel/nodes-panel.fetch.saga.js, frontend/scripts/react-components/nodes-panel/nodes-panel.reducer.js, frontend/scripts/react-components/nodes-panel/nodes-panel.saga.js, frontend/scripts/react-components/nodes-panel/nodes-panel.selectors.js
Fixes to the data serialization in both panels
=> Feat: fix missing data loading

app/controllers/api/public/nodes/destinations_controller.rb, app/controllers/api/public/nodes/exporters_controller.rb, app/controllers/api/public/nodes/importers_controller.rb, app/controllers/api/public/nodes/sources_controller.rb
rather than via another concern because stuff breaks
=> Include pagination concerns directly in controllers

app/models/api/v3/readonly/dashboards/commodity.rb, app/models/api/v3/readonly/dashboards/country.rb, db/migrate/20191205213427_add_year_to_countries_and_commodities.rb, db/structure.sql, db/views/dashboards_commodities_v_v03.sql, db/views/dashboards_countries_v_v03.sql
https://www.pivotaltracker.com/story/show/170147130
Added filtering by year to nodes endpoints and forgot it's also needed for countries / commodities
=> Fixed filtering by year in countries / commodities endpoints

app/services/api/v3/actors/basic_attributes.rb, spec/services/api/v3/actor/basic_attributes_spec.rb
https://www.pivotaltracker.com/story/show/170232266
Use the chart node type to get the right word (municipality, department, ...)
Look up a Paraguay soy actor profile.
=> Removed hardcoded municipalities from description of sourcing regions

db/migrate/20191209224805_create_partitioned_flows.rb
=> fix column type

frontend/scripts/analytics/middleware.js, frontend/scripts/analytics/nodes-panel.events.js, frontend/scripts/analytics/tool.events.js
=> adds some events and fixes others

frontend/scripts/react-components/shared/table-modal/table-modal.component.jsx, frontend/scripts/utils/csv-converter.js
https://www.pivotaltracker.com/story/show/161215942
=> Adds csv download to table modal

Gemfile, Gemfile.lock
https://www.pivotaltracker.com/story/show/170873761
https://stackoverflow.com/questions/59720208/undefined-method-transform-keys-loading-sidekiq-web
Check if `/content/sidekiq` loads
=> Downgraded rack due to issue with sidekiq-web

frontend/browserslist, frontend/package.json, frontend/scripts/actions/app.actions.js, frontend/scripts/actions/data.actions.js, frontend/scripts/index.js, frontend/scripts/react-components/dashboard-root/dashboard-root.actions.js, frontend/scripts/react-components/data-portal/data-portal-form/data-portal-form.component.jsx, frontend/scripts/react-components/home/home.actions.js, frontend/scripts/react-components/legacy-explore/explore.actions.js, frontend/scripts/react-components/logistics-map/logistics-map.actions.js, frontend/scripts/react-components/shared/newsletter/newsletter.actions.js, frontend/scripts/react-components/static-content/static-content.actions.js, frontend/scripts/react-components/team/team.actions.js, frontend/scripts/react-components/tool/tool.actions.js, frontend/scripts/reducers/app.thunks.js, frontend/yarn.lock
- Replace fetch with axios everywhere.
- Load unsupported libraries dynamically.
- Add necessary polyfills
=> updates code to support explorer and google bot

frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget-config.js, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.selectors.js, frontend/scripts/react-components/shared/node-title/node-title.scss, frontend/scripts/react-components/shared/recolor-by/recolor-by-node-legend-summary/recolor-by-item-legend-summary.scss, frontend/scripts/react-components/shared/recolor-by/recolor-by.scss, frontend/scripts/react-components/tool/sankey/recolor-by-legend/recolor-by-legend.scss, frontend/scripts/react-components/tool/sankey/sankey.scss, frontend/styles/_settings.scss
Use sass colors to power the js widget styles
=> use single source for colors

doc/gh-pages/api/trase_public_api_1.1.oas3.yaml
https://www.pivotaltracker.com/story/show/170795110
Version 1.1 of the public API spec, with descriptions of new endpoints to cover the requirements of GFW integration, replacing top_nodes.
=> Proposed endpoints to replace top_nodes in GFW

doc/gh-pages/api/trase_public_api_1.1.oas3.yaml
https://www.pivotaltracker.com/story/show/170797616
Based on optimisation work done for the exporting companies chart, for self preservation it makes sense to simplify the proposed public endpoint.
=> Simplified proposed data endpoint for performance reasons

frontend/scripts/react-components/explore/explore.component.jsx, frontend/scripts/react-components/explore/explore.scss, frontend/scripts/react-components/explore/featured-cards/featured-cards.component.jsx, frontend/scripts/react-components/explore/featured-cards/featured-cards.scss, frontend/scripts/react-components/shared/grid-list-item/grid-list-item.component.jsx, frontend/scripts/react-components/shared/grid-list-item/grid-list-item.scss, frontend/scripts/react-components/shared/icon/icon.scss
https://www.pivotaltracker.com/story/show/171570183
Designs: https://projects.invisionapp.com/d/main#/projects/prototypes/18742050
- Move button on explore page next to the title
- Update grid list item info button styles
Extra: Fix 'None' Button on hover on indicators modal
- Back button: Go to explore page
- Info button: Go to tool and open indicator filter modal on the top navbar or edit map layers modal below the map
=> Feedback fixes - Back button and info button

frontend/scripts/react-components/nav/top-nav/top-nav.scss
Fix, Remove margins from `TopNav`
=> Remove margins from navigation bar

app/services/api/v3/dashboards/filter_companies.rb, app/services/api/v3/dashboards/filter_exporters.rb, app/services/api/v3/dashboards/filter_importers.rb, app/services/api/v3/dashboards/filter_nodes.rb
=> Fixes duplicates on importer countries filter

frontend/scripts/react-components/profile/profile-components/map.component.jsx, frontend/scripts/react-components/profile/profile-components/summary/country-summary.component.jsx, frontend/scripts/react-components/profile/profile-components/summary/place-summary.component.jsx, frontend/scripts/react-components/profile/profile-components/summary/summary-title.component.jsx, frontend/scripts/react-components/profile/profile-components/summary/summary.scss, frontend/styles/_layouts.scss, frontend/styles/layouts/l-profile-country.scss
https://www.pivotaltracker.com/story/show/171568250
We will get the countryName in the future directly from the backend so you won't be able to see the highlighted country yet (In the picture is hardcoded)
Go to one exporter country profile (You would have to have it in the CMS). The map should show
=> Add country map and fix title

frontend/scripts/react-components/home/homepage.scss, frontend/scripts/react-components/shared/newsletter/newsletter-form.component.jsx, frontend/scripts/react-components/shared/newsletter/newsletter.scss
https://www.pivotaltracker.com/story/show/172048162
Added a message when the users write their message and removed it on sent 
Home. Write the email and sent it
=> Add message to accept GDPR conditions

frontend/docs/backend/mbtileserver.mdx, frontend/docs/index.mdx
https://www.pivotaltracker.com/story/show/172497529
Documentation for mbtileserver set-up
=> mbtileserver documentation

config/sitemap.rb
https://www.pivotaltracker.com/story/show/172714989
Submit one profile html / pdf link per node / context for last available year; this needs to be reviewed once the indexer processes the new sitemap, hopefully it would accept more links submitted through the sitemap than at the moment.
Review indexer coverage
=> Submit one profile html / pdf link per node / context for last available year

app/workers/com_trade_refresh_worker.rb
https://www.pivotaltracker.com/story/show/172973192
=> Fixed log output

frontend/scripts/router/nav-links.js
Changes the link on the navbar from 'Trase Finance' to 'Finance'
=> Change label

frontend/scripts/router/nav-links.js
=> Change finance link position

app/models/api/v3/context_node_type_property.rb
https://www.pivotaltracker.com/story/show/173057657
=> Fix for data update process

app/serializers/api/public/country_serializer.rb, app/services/api/public/filter_commodities.rb, app/services/api/public/filter_countries.rb, app/services/api/v3/dashboards/filter_countries.rb
https://www.pivotaltracker.com/story/show/172771029
/api/public/countries?include=commodities
=> Added iso2 to public countries endpoint

app/services/api/v3/actors/basic_attributes.rb
https://www.pivotaltracker.com/story/show/172918023
Exporter group ended up as an importer
=> Exporter summary for exporter group

app/workers/com_trade_refresh_worker.rb
https://www.pivotaltracker.com/story/show/172973192
Exception in worker
=> Fixed uninitialized constant in ComTradeRefreshWorker

app/services/api/v3/flows/filter.rb
https://www.pivotaltracker.com/story/show/173244828
=> Fix other count when in expanded column

frontend/scripts/react-components/explore/explore.scss, frontend/scripts/react-components/shared/dropdown/dropdown.scss, frontend/scripts/react-components/shared/shrinking-spinner/shrinking-spinner.scss
https://www.pivotaltracker.com/n/projects/2380432
Low priority IE fixes
---
=> low priority IE fixes

app/services/api/v3/country_profiles/import_trajectory.rb
https://www.pivotaltracker.com/story/show/173810396
=> Import trajectory included_years array instead of range

app/models/api/v3/chart.rb
https://www.pivotaltracker.com/story/show/173829938
=> Fixed type

frontend/scripts/react-components/profile/profile-components/button-links/button-links.component.jsx, frontend/scripts/react-components/profile/profile-components/summary/actor-summary.component.jsx, frontend/scripts/react-components/profile/profile-components/summary/country-summary.component.jsx, frontend/scripts/react-components/profile/profile-components/summary/place-summary.component.jsx, frontend/scripts/react-components/profile/profile-components/top-destinations-chart.component.jsx, frontend/scripts/react-components/profile/profile-widgets/importing-companies-widget.component.jsx, frontend/scripts/react-components/profile/profile-widgets/sustainability-table-widget.component.jsx, frontend/scripts/react-components/profile/profile-widgets/top-consumers-widget.component.jsx, frontend/scripts/react-components/profile/profile-widgets/top-destinations-widget.component.jsx, frontend/scripts/react-components/profile/profile.component.jsx
none
This pr fixes an issue where we where displaying wrong data on the mini sankey, we now are using the chart.url to fetch the correct information as in (countries/companies) 
**Example issue, here we should display traders not countries** 
Check all profile types and make sure we are using the correct context in the sankey.
=> Fix issue where we where using the wrong data on mini sankey

app/services/api/v3/country_profiles/commodity_totals.rb
Table with commodity exports / imports was previously not sorted
=> Sorting table by commodity exports / imports

app/controllers/api/v3/country_profiles_controller.rb, app/controllers/api/v3/places_controller.rb, app/services/api/v3/profiles/cross_context_top_nodes_chart.rb, app/services/api/v3/profiles/single_context_top_nodes_chart.rb
Related to missing OTHER flow on place profiles: https://www.pivotaltracker.com/story/show/173702389
Same fix as for place profiles
=> Applies OTHER flow to mini sankey charts in country profiles

config/deploy/sandbox.rb, db/migrate/20200521074053_add_subnational_years_to_contexts.rb, db/structure.sql
In preparation for upcoming data upload
Adds an extra column to the contexts table, which will be present in upcoming dump
Merge ahead of upcoming data update
=> Added subnational_years to contexts

app/services/api/v3/country_profiles/basic_attributes.rb, app/services/api/v3/country_profiles/deforestation_trajectory.rb, app/services/api/v3/profiles/stacked_line_chart.rb
https://www.pivotaltracker.com/story/show/174473261
To be tested with the new dump (as on staging)
=> Multi-unit compatibility fix for deforestation trajectory chart

frontend/scripts/react-components/shared/animated-card/animated-card.component.jsx
=> Remove capitalise transform

app/services/api/public/nodes/filter.rb
https://www.pivotaltracker.com/story/show/174641147
=> Fixes duplicated availability objects in public nodes endpoint

frontend/scripts/router/nav-links.js
To be deployed tomorrow morning
https://www.pivotaltracker.com/n/projects/2380432/stories/174795952
https://docs.google.com/document/d/1TwrOlAelmBNeuSEcI971p8K8VJUbkvH5tpjhYVxPjkU/edit
=> change yearbook link to insights

frontend/scripts/react-components/shared/hero/hero.component.jsx
https://www.pivotaltracker.com/n/projects/2380432/stories/174795858
=> update hero sentence

db/migrate/20201007085611_add_index_on_com_trade_commodity_id.rb, db/structure.sql
=> Index on commodity_id to speed up partial refreshing

doc/gh-pages/api/trase_public_api_1.0.oas3.yaml, doc/gh-pages/api/trase_public_api_1.1.oas3.yaml
Also applied to 1.1 draft.
https://www.pivotaltracker.com/story/show/175226772
=> Text changes to public API documentation release version 1.0

frontend/scripts/react-components/explore/explore.selectors.js
We needed a guard
Go to explore without a recent card
=> Dont crash the page if we dont have recentcards

frontend/scripts/tests/explore/explore-selectors.test.js
Remove skipped explore selector test and simplify it
=> Remove skipped test and simplify it

frontend/scripts/react-components/tool/timeline/timeline.component.jsx
Guard for subnationalYears as logistic maps was crashing
=> Guard for subnationalYears as logistic maps was crashing

config/deploy.rb, lib/tasks/map_attributes.rake
=> Schedule refreshing map attributes after deploy

app/controllers/api/v3/sankey_card_links_controller.rb, app/services/api/v3/sankey_card_links/response_builder.rb, spec/services/api/v3/sankey_card_links/response_builder_spec.rb
https://appsignal.com/vizzuality/sites/5a8317dfe2954e5d54c8cf8c/exceptions/incidents/281
=> Whitelist level before inserting into query

frontend/html/includes/_head.ejs, frontend/scripts/react-components/profile/profile-widgets/summary-widget.component.jsx, frontend/scripts/utils/stripHtml.js
This pr adds some basic meta tags (social, description, meta title) for profiles for better social sharing. 
Note, needed to add data-react-helmet="true" to _head, otherwise the old tags wont be replaced.
=> fix profile metatags

app/services/api/v3/places/basic_attributes.rb, spec/services/api/v3/places/basic_attributes_spec.rb
https://app.asana.com/0/1187619191620560/1192587389376506/f
Tooltip for commodity area had hardcoded commodity name in it.
=> Fixes hardcoded commodity name

app/services/api/v3/import/importer.rb, app/services/api/v3/refresh_profiles.rb, config/database.yml, config/sidekiq.yml, lib/tasks/basic_attributes.rake
https://app.asana.com/0/1187619191620560/1196299257993122/f
Improvements to refreshing pre-computed basic attributes
=> Service object that first clears, then schedules refreshing of profiles

app/services/api/v3/countries_com_trade_indicators/importer_service.rb, app/services/api/v3/countries_wb_indicators/importer_service.rb, lib/tasks/db_country_profiles.rake
https://app.asana.com/0/1195054825337974/1197993057162668/f
Applies names of newly added header attributes
=> Country profiles really finishing touches

app/models/api/v3/readonly/node_with_flows.rb
…
https://app.asana.com/0/1187619191620560/1196299257993122/f
Fixing summary update statement, so that it doesn't update across all nodes with same id
=> Bugfix: Incorrect commodities on actor profiles

frontend/scripts/react-components/home/home-video/home-video.component.jsx
Using youtube privacy enhanced mode to remove the cookies:
https://support.google.com/youtube/answer/171780?hl=en-GB
=> Use youtube no cookie mode

app/services/api/v3/countries_wb_indicators/wb_request.rb
https://app.asana.com/0/1187619191620560/1199573634543486/f
Ranks were calculated across regions and countries, resulting in nonsensical values.
`SELECT * FROM countries_wb_indicators where name = 'NY.GDP.MKTP.CD' and year = 2019 order by rank`
=> Fixed WB country ranking calculation (rejected regions)

app/services/api/v3/country_profiles/basic_attributes.rb
https://app.asana.com/0/1187619191620560/1199573634543486/f
Ordinalize ranks in country summary
=> Ordinalize ranks

frontend/styles/_settings.scss
Update some wood pulp thematic colours
=> Update thematic colours

frontend/html/includes/_head.ejs
Add Google analytics V4 tags to root
=> GA4 support

app/services/api/v3/countries_wb_indicators/indicators_list.rb
https://app.asana.com/0/1187619191620560/1199573634543486/f
New indicator added to the list of indicators to pull from World Bank API
Check the values are present after full refresh
=> AG.SRF.TOTL.K2 for country surface area

frontend/scripts/react-components/profile/profile-components/scatterplot/scatterplot.component.jsx, frontend/scripts/react-components/profile/profile-components/scatterplot/scatterplot.scss, frontend/scripts/react-components/profile/profile-widgets/importing-companies-widget.component.jsx, pull_request_template.md
https://app.asana.com/0/1187619191620560/1199241958938734/f
Added some x and y axis labels based on the dimensions unit. These change when we select a different indicator from the tabs
=> Add labels to scatterplot

frontend/scripts/react-components/shared/new-footer/footer.scss
Add responsive design to the new footer, only mobile
=> Responsive, missing tablet

.github/workflows/rspec.yml
=> Back end CI build using Github Actions

app/services/api/v3/country_profiles/external_attribute_value.rb
https://app.asana.com/0/1187619191620560/1199573634543486/f
Check a country with no values for 2019
=> Fall back to previous year's value for WB indicators

app/services/api/v3/actors/basic_attributes.rb, frontend/scripts/react-components/dashboard-element/dashboard-widget/ranking-widget/ranking-widget.component.jsx, frontend/scripts/react-components/profile/profile-components/summary/summary-title.component.jsx
https://app.asana.com/0/1195054825337974/1199601330969645/f
=> uppercase company titles

app/controllers/api/v3/newsletter_subscriptions_controller.rb, frontend/scripts/react-components/shared/button/button.scss, frontend/scripts/react-components/shared/new-footer/footer.component.jsx, frontend/scripts/react-components/shared/new-footer/footer.scss, frontend/scripts/react-components/shared/newsletter/newsletter-form.component.jsx, frontend/scripts/react-components/shared/newsletter/newsletter.scss
https://projects.invisionapp.com/d/main/#/console/20810309/437845102/inspect
The form submit won't work as we don't send the last name and we send country instead. They should update their form. Maybe we should add the last name too
=> Update footer design

config/deploy/production.rb
Update the IP for production deploy
=> Update production server

app/services/api/v3/country_profiles/basic_attributes.rb
https://app.asana.com/0/inbox/1191186791596033/1199573634543486/1199542839763336
=> Update text of profiles to reflect surface area rather than land mass

frontend/scripts/react-components/profile/profile-components/mini-sankey/mini-sankey.component.jsx
https://app.asana.com/0/1187619191620560/1199581760549288/f
Fix truncated name on the mini-sankey
=> Fix truncated name

frontend/scripts/react-components/dashboard-element/dashboard-widget/ranking-widget/ranking-widget.component.jsx
https://app.asana.com/0/1195054825337974/1199601330969645/f
Top 50 wood suppliers included in the uppercase check
`/flows/data-view?toolLayout=1&countries=107&commodities=87&selectedColumnsIds=0_8-1_22-2_17-3_16` and check top 50 wood suppliers.
=> fix wood supplier title uppercase

frontend/scripts/react-components/nav/top-nav-redesign/top-nav-redesign.scss
https://app.asana.com/0/1187619191620560/1199900373301612/f
Add a min-width for search
Go to one profile
http://localhost:8081/profile-country?nodeId=68&commodityId=1
=> FIx navbar

frontend/scripts/react-components/data-portal/download-selector.component.jsx, frontend/scripts/react-components/profile/profile-components/line/line.component.jsx
Add uppercase scenario in two more locations found during testing.
=> uppercase companies in two more locations

app/services/api/v3/actors/basic_attributes.rb, app/services/api/v3/places/basic_attributes.rb
https://app.asana.com/0/1187619191620560/1199601330969645/f
before:
after:
Also, please, whenever touching actor basic attributes, remember it is hard cached on the database and that needs to be refreshed for changes in the service to take effect.
=> Upcase all things

frontend/scripts/react-components/profile/profile.container.jsx
Completely forbid the rendering of profile countries without the tag activated. It will render a blank page
https://localhost:8081/profile-country...
=> Prevent rendering of profile countries

frontend/scripts/react-components/dashboard-element/dashboard-element.selectors.js
Transform data view sources to uppercase
=> Uppercase data view sources

app/services/api/v3/places/basic_attributes.rb
https://app.asana.com/0/1198886845396491/1199565010043907/f
Hardcoded override in summary text
=> Pulpwood rather than wood pulp in summary

frontend/scripts/react-components/dashboard-element/dashboard-element.selectors.js
https://app.asana.com/0/1187619191620560/1200058680353620/f
Check the dynamic sentence on the data view. On several languages
=> Change wording and translate

app/services/api/v3/country_profiles/commodity_totals.rb
https://app.asana.com/0/0/1200168441943715/f
Convert kg to tonnes in exports / imports column
=> Convert commodity exports / imports to tonnes

app/services/api/v3/country_profiles/basic_attributes.rb
https://app.asana.com/0/0/1200124803845199/f
Changed HDI sentence to reflect the fast that the value is a score, not a rank
=> Changed HDI sentence

app/services/api/v3/country_profiles/basic_attributes.rb
https://app.asana.com/0/0/1200168441943759/f
=> So that the sentence reads "XXX is a signatory to the New York ... and the Amsterdam ..."

frontend/scripts/react-components/dashboard-element/dashboard-element.selectors.js, frontend/scripts/react-components/dashboard-element/dashboard-widget/dynamic-sentence-widget/dynamic-sentence-widget.selectors.js, frontend/scripts/react-components/dashboard-element/dashboard-widget/node-indicator-sentence-widget/node-indicator-sentence-widget.selectors.js, frontend/scripts/utils/transifex.js
Add a couple more translation strings to transifex
=> Add some strings to transifex

frontend/scripts/constants.js
https://app.asana.com/0/0/1200168441943715/f
Remove decimals from exports indicator
=> Remove decimals from exports indicator

app/services/api/v3/map_attributes_export.rb, frontend/docs/backend/map_attributes_carto_export.mdx
https://github.com/Vizzuality/trase/pull/1807
=> Fixed incorrect object initialisation

app/services/api/v3/map_layers/map_attribute_filter.rb, app/services/api/v3/node_attributes/filter.rb, db/migrate/20210426164057_remove_aggregated_buckets_function.rb, db/structure.sql
https://app.asana.com/0/1199888630756445/1200151592420074/f
Apply aggregation_method to node_attributes endpoint
=> Apply aggregation_method to node_attributes endpoint

app/services/api/v3/country_profiles/commodity_totals.rb
https://app.asana.com/0/0/1200168441943721/f
If nothing to show for wood pulp, do not show wood pulp at all in this table.
=> Removed empty rows from commodity top exports table

app/services/api/v3/map_attributes_carto_upload.rb, app/services/api/v3/map_attributes_export.rb
The steps are as follows:
- create backup table
- create new table
- copy data (if this fails, restore table from backup)
- remove backup table
- index new table
=> Drop / create table when uploading data to Carto

app/services/api/v3/map_attributes_carto_upload.rb
New Carto tables with uploaded map attributes are created private as a default. This change sets them to public.
=> Make the new table public

app/services/api/v3/map_attributes_carto_upload.rb
Making the table public doesn't seem to work on sandbox, maybe there's a race condition. Tried to resolve by only making it public following successful copy.
=> Simplify by avoiding a restore scenario

frontend/scripts/constants.js
https://app.asana.com/0/0/1200168441943718/f
Before:
After:
Also applied to "imports" column on importer country profiles.
=> Commodity exports / imports rounded to thousands

frontend/scripts/app/app.component.jsx, frontend/scripts/react-components/shared/new-button/button.component.jsx, frontend/scripts/react-components/shared/new-button/button.scss, frontend/scripts/react-components/shared/new-button/new-button.js, frontend/scripts/react-components/shared/new-cookie-banner/cookie-banner.component.jsx, frontend/scripts/react-components/shared/new-cookie-banner/cookie-banner.scss, frontend/scripts/react-components/shared/new-cookie-banner/new-cookie-banner.jsx
https://app.asana.com/0/0/1199884863618291/f
Update the cookie banner
I have created a new-cookie-banner and a new-button with different styles
We will need the UI kit to confirm that we need the new button
Try on an incognito window so you can see the cookie banner
=> Create new cookie banner style

app/services/api/v3/country_profiles/commodity_totals.rb
Caused by changes to fetching preloaded attributes value + year
=> Fixed regression in commodity totals chart (cnt)

app/services/api/v3/flows/filter.rb
https://app.asana.com/0/1199888630756445/1200151592420074/f
Use SUM for single year and aggregation_method for multi-year.
=> SUM for single year, apply aggregation method for multi-year

frontend/scripts/react-components/nav/top-nav-redesign/top-nav-redesign.scss, frontend/scripts/react-components/new-home/entrypoints/entrypoints.scss
- Text was overflowing and menu cards were cut
The solutions are not perfect but good enough
=> Fix safari and landing

frontend/scripts/react-components/profile/profile-components/mini-sankey/mini-sankey.component.jsx, frontend/scripts/react-components/profile/profile-widgets/top-consumers-widget.component.jsx, frontend/scripts/react-components/profile/profile.component.jsx
https://app.asana.com/0/0/1200168442660951/f
There was a request to invert the mini-sankey of the importer countries, start it with the exports and end it with the country. 
Some tweaking was needed as its a custom component
=> Invert mini-sankey for importer countries

app/services/api/v3/node_attributes/filter.rb
https://appsignal.com/vizzuality/sites/5ac78a01fc940e7ec5927d5b/exceptions/incidents/149
=> Fix nil returned by reduce when no map attributes

app/services/api/v3/flows/filter.rb
Also, finally fix the ancient todo regarding sorting of unknown nodes
https://app.asana.com/0/0/1200238037572780/f
Problem:
=> Apply order clause to outer query, not subquery

app/services/api/v3/country_profiles/import_trajectory.rb
https://app.asana.com/0/0/1200168442660956/f
Regression from https://github.com/Vizzuality/trase/pull/1850
=> Fix for regression related to how indicator values are now returned

frontend/scripts/react-components/tool/map/map.selectors.js
https://app.asana.com/0/1199888630756445/1200433887053720/f
The tooltip needed the other information (map indicators)
=> Remove tooltip data from map

frontend/scripts/react-components/nav/top-nav/top-nav.scss, frontend/scripts/react-components/shared/footer/footer.scss
https://app.asana.com/0/1199888630756445/1200433887053720/f
Last responsive changes in nav-bar and footer
=> Responsive changes

frontend/scripts/react-components/shared/footer/footer.component.jsx
https://app.asana.com/0/1200542925644189/1200571929063254/f
Link to the contact page on a new tab
=> Open contact in a new tab

Gemfile, Gemfile.lock, spec/responses/health_spec.rb
https://app.asana.com/0/0/1200844293947954/f
Implemented using a gem
/health
=> Health check endpoint

frontend/styles/_settings.scss
https://app.asana.com/0/1187619191620560/1201075196122772/f
Add Cote d'ivoire ecoregions category colors
=> Add Cote d'ivoire ecoregions category colors

frontend/scripts/react-components/nav/sidebar-nav/sidebar-nav.scss
Little adjustment for titles on the sidebar
=> Dont wrap trase title

frontend/scripts/react-components/tool-layers/tool-layers.selectors.js
Indonesia - Wood Concession Map
We needed to add an exception for concessions on this context
=> Add exception

frontend/scripts/react-components/shared/tool-bar/tool-bar.component.jsx, frontend/scripts/react-components/shared/tool-bar/tool-bar.js, frontend/scripts/react-components/shared/tool-bar/tool-bar.scss, frontend/scripts/react-components/shared/tool-bar/tool-bar.selectors.js, frontend/scripts/react-components/tool/sankey/sankey.component.jsx, frontend/scripts/react-components/tool/sankey/sankey.js
https://app.asana.com/0/0/1201338310203375/f
Add reset button and clear the one on the menu
=> Clear selection button

frontend/scripts/react-components/tool/sankey/sankey.component.jsx, frontend/styles/_settings.scss
[link
](https://app.asana.com/0/1201503005195814/1197305588507210/f)
Provide default colors if we don't have any declared on settings.scss
=> Add default colors for recolor by

app/services/api/v3/database_validation/checks/declared_years_match_flow_attributes.rb, app/services/api/v3/database_validation/checks/declared_years_match_node_attributes.rb
[Please include the link(s)](https://app.asana.com/0/1201503005195814/1201727304221097/f)
Unrelated fixes for the validation report, trying to see if the report would have caught the issue in Asana.
=> Fixed nil comparison in sort

frontend/scripts/react-components/cta/cta-styles.scss
https://app.asana.com/0/1201503005195814/1201743452746170/f
Fix responsive CTA display
=> Fix responsive CTA display

app/services/concerns/api/v3/dashboards/call_with_query_term.rb, spec/services/api/v3/dashboards/filter_destinations_spec.rb, spec/services/api/v3/dashboards/filter_exporters_spec.rb, spec/services/api/v3/dashboards/filter_importers_spec.rb, spec/services/api/v3/dashboards/filter_sources_spec.rb
https://appsignal.com/vizzuality/sites/5a8317dfe2954e5d54c8cf8c/exceptions/incidents/329?timestamp=2022-02-10T04%3A42%3A12Z
So embarassing I'd rather skip the comment, but indeed - there was an SQL injection vulnerability in FTS search.
=> Fixed SQL injection when searching dashboards nodes

frontend/scripts/index.ejs
https://app.asana.com/0/1201503005195814/1201506190953082/f
Add script to use usersnap
=> Add usersnap widget script

frontend/scripts/utils/formatValue.js
Use 0 decimals for powerOfTenForRounding = 0
=> Use 0 decimals for powerOfTenForRounding = 0

frontend/scripts/react-components/tool/column-selector/column-selector.component.jsx
https://app.asana.com/0/1201503005195814/1202017897983357/f
The last column selector text was exceeding the screen limit
=> Improve last column selector position

frontend/scripts/app/app.component.jsx, frontend/scripts/react-components/shared/google-translate-script/google-translate-script.component.jsx, frontend/scripts/react-components/shared/google-translate-script/google-translate-script.jsx
https://app.asana.com/0/1202078762437448/1202039995135590/f
Add google translate script to sandbox for testing
=> Add google translate script to sandbox

frontend/scripts/constants.js, frontend/scripts/react-components/tool-layers/tool-layers.selectors.js, frontend/scripts/react-components/tool/sankey/sankey-hooks.js, frontend/scripts/react-components/tool/sankey/sankey.component.jsx
https://app.asana.com/0/1196306894127399/1202170573125887
Add selection value for the tooltip of the nodes of the last column
=> Add selection volume on tooltip and extract hooks

frontend/scripts/react-components/explore/explore.selectors.js
https://app.asana.com/0/1202078762437448/1202039995135596/f
Change default text of cards depending if they are subnational or not
=> Change full supply chain text

db/scripts/configuration_import/configuration_importer.rb
This uses the json export format from the old production database to restore import country profiles that went missing after renaming COUNTRY -> COUNTRY OF DESTINATION
=> Restoring import country profiles configuration from previous version of database

frontend/scripts/react-components/cta/cta-component.jsx, frontend/scripts/react-components/cta/cta-styles.scss, frontend/scripts/react-components/cta/cta-versions-data.jsx
https://app.asana.com/0/1202544575649341/1202552347527525/f
Add new fixed CTA for explore page
=> Add fixed CTA

frontend/scripts/app/helpers/sortVisibleNodes.js
https://app.asana.com/0/1202544575649341/1202701560219155/f
Sort Unknown nodes before node with generic 'UN KNOWN' node
=> Sort nodes if both are unknown

frontend/scripts/index.jsx, frontend/scripts/react-components/nav/top-nav/top-nav.scss, frontend/scripts/react-components/shared/grid-list-item/grid-list-item.component.jsx, frontend/styles/_gtranslate.scss
https://app.asana.com/0/1202078762437448/1202039995135590/f
- Remove transifex translation when we use the google translate
- Hide the top translate bar
- Temporarily disable the expore items tooltip to prevent a crash due to the manipulation of the DOM on unmounted components
=> Fix crash and remove top navbar

frontend/scripts/index.ejs, frontend/scripts/react-components/shared/google-translate-script/google-translate-script.component.jsx
https://app.asana.com/0/0/1202914489293828/f
Limit the translate languages on google translate selector
=> Limit the languages on google translate

frontend/.vscode/launch.json, frontend/scripts/app/helpers/getChoropleth.js, frontend/scripts/react-components/shared/grid-list-item/grid-list-item.scss, frontend/scripts/react-components/tool/map/map.hooks.js
https://app.asana.com/0/1202544575649341/1202970984310311/f
Fix color shown on the map when values are negative
=> Fix negative color on map

.github/workflows/auto_deploy_demo.yml, .github/workflows/auto_deploy_develop.yml, .github/workflows/deploy_production.yml, .github/workflows/documentation.yml, .github/workflows/tests.yml
Hoping to fix https://github.com/Vizzuality/trase/actions/runs/3541646669/jobs/5946169609
=> Busting gems cache

frontend/scripts/react-components/tool/sankey/node-interaction-utils.js, frontend/scripts/react-components/tool/sankey/sankey.component.jsx
https://app.asana.com/0/1203966725731677/1203323518134769/f
This PR adds an exception on the Sankey when any deforestation exposure unit is selected to not show the indicator on the tooltip for the first column
=> Add exception and extract function

.github/workflows/auto_deploy_demo.yml, .github/workflows/auto_deploy_develop.yml, .github/workflows/deploy_production.yml, .github/workflows/tests.yml
Please include the link(s)
Please include a summary of the change
=> Suppress code coverage publishing on pull request events

.env.sample, .standard_todo.yml, Gemfile, Gemfile.lock, app/controllers/api/v3/newsletter_subscriptions_controller.rb, app/services/api/v3/create_newsletter_subscription.rb, spec/controllers/api/v3/newsletter_subscriptions_controller_spec.rb, spec/services/api/v3/create_newsletter_subscription_spec.rb
https://app.asana.com/0/0/1204215763287078/f
extracting BE changes from #2195
=> Mailchimp gem upgrade and logic update to handle 2 audiences

.standard_todo.yml, app/controllers/api/v3/dashboards/companies_controller.rb, app/services/concerns/api/v3/dashboards/call_with_query_term.rb, spec/controllers/api/v3/dashboards/companies_controller_spec.rb
https://appsignal.com/vizzuality/sites/5a8317dfe2954e5d54c8cf8c/exceptions/incidents/404/samples/last
=> Fixes exception when questionmark in query term

package.json, yarn.lock
=> Upgraded webpack-dev-server to enable upgrading node-forge

package.json, yarn.lock
Vulnerability in dependent libs
=> Upgraded webpack and webpack-cli

frontend/docs/backend/mbtileserver.mdx
=> Update to mbtileserver docs

app/services/api/v3/profiles/indicators_table.rb
https://app.asana.com/0/1205165240647409/1199571503392690/f
The name of that column is hardcoded in the BE.
=> Renamed Score column in the indicators table to Value

frontend/docs/frontend/map.mdx, frontend/scripts/react-components/tool-layers/tool-layers.selectors.js
https://app.asana.com/0/1205165240647409/1205376096923351/f
Allow layers on the map that are year dependant
=> Allow layers with year ranges

app/services/api/v3/flows/filter.rb, app/services/api/v3/flows/result.rb, spec/services/api/v3/flows/filter_spec.rb
https://app.asana.com/0/1205165240647409/1205354181768983/f
Same as https://github.com/Vizzuality/trase/pull/2306, but returning values for flows (rather than just nodes).
=> Add dependent indicators to tooltips in flows

app/services/api/v3/flows/result.rb, frontend/scripts/app/helpers/splitLinksByColumn.js, frontend/scripts/react-components/tool/sankey/node-interaction-utils.jsx, frontend/scripts/react-components/tool/sankey/sankey.component.jsx
https://app.asana.com/0/1196306894127399/1205354181768983
Fixes lack of extra attributes values when a recolor by selected
=> Associates values of extra attributes correctly when recolor by used

app/services/api/v3/flows/filter.rb
https://app.asana.com/0/1205165240647409/1205720134309606/f
Fixes a regression introduced when reworking the flows logic to support subunits
Pulpwood planted area and Natural forest area should not be SUMed in range mode
=> Restored logic to use specific aggregation method
