app/controllers/download_controller.rb, app/models/flow_download_query_builder.rb, app/models/materialized_flow.rb, db/migrate/20170314095630_enable_tablefunc_extension.rb, db/migrate/20170314113737_create_some_indexes.rb, db/migrate/20170314115226_create_node_flows.rb, db/migrate/20170314115306_create_flow_indicators.rb, db/migrate/20170316135218_update_materialized_flows_to_version_2.rb, db/structure.sql, db/views/flow_indicators_v01.sql, db/views/materialized_flows_v02.sql, db/views/node_flows_v01.sql, spec/factories/flow.rb, spec/models/flow_download_query_builder_spec.rb, spec/support/two_flows_context.rb
- enables filtering by selected quants, quals and inds (previously only quants supported)
- enables pivot csv download
Note: requires `rake db:migrate` and it does take a while to produce an aggregated view of data for the downloads
The currently supported set of parameters for the download endpoint is as follows:
- `context_id`: integer
- `exporter_ids, importer_ids, countries_ids`: arrays of integers
- `indicators`: array of backend_names of indicators (quals, quants or inds, the assumption being their identifiers are unique across the 3 tables)
- `pivot`: set to 1 if the pivot version is required, empty otherwise
- `separator`: 'comma' or 'semicolon' (defaults to comma)
=> Enabled pivot download

app/enumerations/node_type_name.rb, app/models/flow_download_query_builder.rb, db/migrate/20170316135218_update_materialized_flows_to_version_2.rb, db/migrate/20170323090506_update_materialized_flows_to_version_3.rb, db/structure.sql, db/views/flow_indicators_v02.sql, db/views/materialized_flows_v03.sql, db/views/node_flows_v01.sql, db/views/node_flows_v02.sql, spec/models/flow_download_query_builder_spec.rb, spec/support/two_flows_context.rb
This removes the previously existing hardcoded conditions with information from `context_nodes` and  `context_indicators` to decide which node goes in which column and what indicators are enabled.
=> Make downloads great again

app/models/place_attributes.rb
Resolves #17 - apparently for some municipalities the biome value might be missing (applied the same check to state)
=> Puts checks in place where values might be missing

app/models/flow_stats_for_node.rb, app/models/place_attributes.rb
I believe it helps with most indicators (e.g. water scarcity, fires), still need to check on some odd empty rows in "other environmental indicators" but this at least should sort out the default selected tab.
https://basecamp.com/1756858/projects/12498794/todos/308418561
=> Do not filter non-temporal indicator values by year for ranking

app/models/actor_attributes.rb, app/models/flow_stats_for_node.rb, app/models/node.rb
Adds importer summary as discussed here:
https://basecamp.com/1756858/projects/12498794/todos/321177482
Important thing is: both summaries now use flows data (Volume quant) rather than quant data (SOY_ quant) to calculate the numbers of tons and derived values; I have checked that the calculated values for exporters / importers match those that were pre-calculated. This does NOT yet remove dependency on the SOY_ quant entirely, as it is still used in other places.
Bunge exporter:
```
Bunge was the largest exporter of soy in BRAZIL in 2015, accounting for 11,548 thousand tons. This is a 9% decrease vs the previous year. As an exporter, Bunge sources from 835 municipalities, or 40% of the soy production municipalities. The main destination of the soy exportered by Bunge is China, accounting …
```
=> Importer summary + refactored exporter summary

app/models/actor_attributes.rb
Removes references to `SOY_` quant in remaining profile calculations.
- replaces `node_quants` with `flow_quants` calculations in the "exporting companies" scatterplot
- removes a top-level attribute `total_soy_2015` which seems obsolete
https://basecamp.com/1756858/projects/12498794/todos/325807711
=> Removed SOY_ quant from exporting companies scatterplot

db/migrate/20171101111009_rename_type_to_original_type.rb, db/schema_comments.yml, db/structure.sql, db/views/attributes_mv_v02.sql, db/views/download_attributes_mv_v02.sql, db/views/map_attributes_mv_v02.sql, db/views/recolor_by_attributes_mv_v02.sql, db/views/resize_by_attributes_mv_v02.sql, lib/tasks/db_revamp_copy.rake
I made the mistake of calling a column in `attributes_mv` materialized view `type`, because originally that mview was a table and I thought this might be useful for an STI scenario with Qual / Quant / Ind inheriting from Attribute. Because of later changes this idea became obsolete and having a column called `type` became very problematic for Rails reasons, so this fixes it by renaming to `original_type` which goes well with `original_id`. I had to redefine all the `xxx_attributes_mv` as well, as this is a joining column.
=> Changes column name from type to original_type

app/controllers/api/v3/contexts_controller.rb, app/serializers/api/v3/contexts/context_serializer.rb, app/serializers/api/v3/contexts/recolor_by_attribute_serializer.rb, app/serializers/api/v3/contexts/resize_by_attribute_serializer.rb, config/routes.rb, doc/swagger.yaml, spec/support/gold_master_urls.yml, spec/version_migration/get_contexts_spec.rb
I think V3 endpoints are not used anywhere yet, so proposing to rename `/get_contexts` -> `/contexts`.
I also added a swagger file with `/contexts` documented and a new convention for other endpoints names proposed:
| old | new |
|-----|----|
|/api/v2/get_contexts | /api/v3/contexts|
|/api/v2/get_columns| /api/v3/context/{context_id}/columns|
|/api/v2/get_map_base_data| /api/v3/context/{context_id}/map_groups|
|/api/v2/indicators| /api/v3/context/{context_id}/download_attributes|
|/api/v1/get_flows| /api/v3/context/{context_id}/flows|
|/api/v2/get_all_nodes| /api/v3/context/{context_id}/nodes|
|/api/v1/get_nodes| /api/v3/context/{context_id}/nodes/attributes|
|/api/v2/get_actor_node_attributes| /api/v3/context/{context_id}/nodes/{id}/actor|
|/api/v2/get_place_node_attributes| …
=> Contexts endpoint renamed and documented

app/controllers/api/v3/map_groups_controller.rb, app/controllers/api/v3/newsletter_subscriptions_controller.rb, app/models/api/v3/map_attribute.rb, app/models/api/v3/map_attribute_group.rb, app/models/api/v3/readonly/map_attribute.rb, config/database.yml, config/routes.rb, db/migrate/20171130103917_update_materialized_map_attributes_to_version_3.rb, db/schema_comments.yml, db/structure.sql, db/views/map_attributes_mv_v03.sql, doc/swagger.yaml, spec/support/contexts/brazil/brazil_context_layers.rb, spec/support/gold_master_urls.yml, spec/version_migration/get_map_base_data_spec.rb
Created the v3 endpoint for map_groups.
There are two things missing (for which I'll need the help of @agnessa)
1 - The gold_master_urls file should have a way to add the `context_id` to the url that is not through params (I'll check where this is being used)
2 - I added the new fields of the `map_groups_mv` to the `schema_comments.yml` but those were not inserted in the `structure.sql`. I'll have to check where this is done.
Also, note that the test is not comparing the key `aggregateMethod` as this was always `nil` in v2.
=> Added the v3 endpoint for map groups

frontend/html/profile-actor.ejs, frontend/scripts/components/profiles/scatterplot.component.js, frontend/styles/components/profiles/scatterplot.scss
- Addresses the first of the issues mentioned in #138 .
=> fix: removes Land use [Ha] from scatterplot legend

frontend/scripts/react-components/tool/nav/dimensional-selector.component.js
- Refactors a little bit the `<DimensionalSelector />` cause DRY.
- Prevents sankey reloading when selecting twice the same list item.
Fixes: #105
=> fix: prevents cc-selector reloading on selected double-click

frontend/scripts/actions/tool.actions.js, frontend/scripts/containers/shared/search-react.container.js, frontend/scripts/react-components/shared/search.component.js, frontend/scripts/utils/isNodeColumnVisible.js
- Enables `importer / exporter` selection on search.
- Separates sibling nodes selection when one of the nodes is not in a visible column.
=> feat: select sibling nodes

config/application.rb, frontend/public/.htaccess
because https://blog.arkency.com/2014/11/dont-forget-about-eager-load-when-extending-autoload/
=> Fix class loading issue in production

app/services/api/v3/download/flow_download_query_builder.rb
This fixes the root cause of #204 - the fact that lookup for the pivoting function failed when using the `revamp` connection. But another problem persists with that endpoint, namely for Brazil-Soy the machine runs out of memory when zipping the response. Smaller contexts work.
=> Schema-qualified call to extension function

lib/schema_revamp.rb
I needed to run the copy task again and realised copying download_versions was broken.
=> Fix copying download versions after partial unique index put in place

.env.sample, Capfile, Gemfile, Gemfile.lock, README.md, config/appsignal.yml
We have previously removed appsignal as I was under the impression we won't continue using it, but alas we still do, which is great so let's put this back in. The push api key has not changed and is still in the env files for all servers so this should be picked up without any further configuration after deploy.
=> Re-added appsignal

frontend/scripts/react-components/profiles/mini-sankey.component.jsx
This PR addresses #231 .
Basically what happened was that the starting point of the flow was equal to the ending point + separator in some edge cases. What we do now is round up when calculating the height and this way we make sure that the difference between ending and starting is bigger than decimal points.
I also changed the way the units was shown because there were cases where the flow equaled `0.09% or lower` and the legend displayed `0%`. Now it displayes `< 0.1%`
=> fix: if sankey flow height matches separator height not appears

frontend/scripts/actions/tool.actions.js
This is another side effect of setting the default state for the tool reducer. in this case, we went from undefined to an array with two nulls. so we need to take that into account
Fixes the part of  https://github.com/Vizzuality/trase/issues/247 concerning the default choropleth layer changes, together with config changes on staging (already done)
=> Fix issue preveting loading default context layer

config/routes.rb, frontend/scripts/utils/getURLFromParams.js
routes starting with /content so that requests are correctly routed to backend
=> Prefix static content routes with /content

.codeclimate.yml, app/controllers/api/v3/contexts_controller.rb, app/controllers/api/v3/top_nodes_controller.rb, app/models/api/v3/context.rb, app/serializers/api/v3/contexts/context_serializer.rb, app/services/api/v3/actor_node/basic_attributes.rb, app/services/api/v3/actor_node/sustainability_table.rb, app/services/api/v3/actor_node/top_nodes_summary.rb, app/services/api/v3/place_node/basic_attributes.rb, app/services/api/v3/place_node/mini_sankey.rb, app/services/api/v3/top_nodes/response_builder.rb, config/routes.rb, doc/swagger.yaml, lib/api/v3/profiles/top_nodes_for_context_list.rb, lib/api/v3/profiles/top_nodes_list.rb, lib/tasks/gold_master.rake, spec/responses/api/v3/top_nodes_spec.rb, spec/services/api/v3/top_nodes/response_builder_spec.rb, spec/support/gold_master_urls.yml, spec/support/schemas/v3_contexts.json, spec/support/schemas/v3_top_nodes.json
I believe both the top destination countries and top exporters visualisations can be served by this endpoint, parametrised by `context_id`, `year` and `column_id` (node type id). By default returns 10 top nodes, but can be controlled with `n_nodes` parameter.
Top exporters for context:
`/api/v3/contexts/1/top_nodes?year_start=2014&year_end=2015&column_id=6`
Top destination countries for context:
`/api/v3/contexts/1/top_nodes?year_start=2014&year_end=2015&column_id=8`
```
{
"data":{
"context_id":1,
"indicator":"Trade volume",
"unit":"Tn",
"targetNodes":[
{
"id":684,
"name":"CHINA",
"height":0.424452686663284,
"value":41375771.5613432
},
{
"id":424,
"name":"BRAZIL",
"height":0.2826774040085104,
"value":27555475.7015545
},
{
"id":1840,
"name":"NETHERLANDS",
"height":0.0402013223456854, …
```
=> Added top nodes endpoint

app/models/content/post.rb, spec/models/content/post_spec.rb
this happened when you edited a highlighted post and did not change the value of the highlighted flag - it would de-highlight itself because of the `before_save` callback
=> Prevent before_save callback from setting highlighted to false

frontend/scripts/reducers/helpers/getChoropleth.js, frontend/scripts/templates/tool/map/legend-choro.ejs
This PR addresses a regression on the map choropleth and choropleth legend when it's dual dimensioned. The bucket styles needed to be updated when the buckets were expanded.
=> fix: choropleth bucket calculations

frontend/scripts/components/tool/sankey.component.js, frontend/scripts/pages/tool.page.jsx
This PR fixes crash when going to profile pages through the sankey and then clicking back button. Also removes event listeners for sanity's sake.
=> fix: avoids race condition and removes event listeners

app/admin/api/v3/database_update.rb, app/admin/api/v3/database_validation.rb, app/admin/dashboard.rb, app/controllers/application_controller.rb, config/initializers/active_admin.rb, spec/controllers/admin/data_validation_controller_spec.rb, spec/controllers/admin/database_update_controller_spec.rb, spec/factories/content/user.rb
Just so that no-one is tempted, this hides the relevant sections of the admin menu in production. Those operations are only meant to be run in integration environment.
=> Disable database updates & database validations in production

frontend/scripts/actions/tool.actions.js, frontend/scripts/components/tool/sankey.component.js
This PR includes a fix to avoid map fitbounds dance 👯.
Basically, we abort requests that haven't been returned to prevent old requests squashing newer ones.
=> fix: avoids map fitbounds dancing

app/controllers/application_controller.rb
Based on the assumption that this only applies to Varnish, due to the fact that we're using SSL, let's keep it the same as currently in production to better see the effect of cache purging on the effectiveness of cache.
=> Increased s-maxage

db/migrate/20180313091306_remove_old_tables.rb
I was recreating my local database from the latest production dump and `remove_old_tables` migration didn't work for me. The script was trying to delete `pg_stat_statements` VIEW using `DROP TABLE` command. I'm fixing the listing of tables taking only those of `BASE TABLE` type.
=> Fixing remove_old_tables migration

frontend/scripts/constants.js, frontend/scripts/react-components/home/slider-section.component.jsx, frontend/scripts/react-components/home/story-tile.component.jsx, frontend/scripts/react-components/static-content/markdown-renderer/markdown-renderer.component.jsx
This PR includes behaviour to allow us to translate links urls. How does it work?
It will add a special transifex property to the `<a>` tags that need translating their href.
This is applied for document links only, so it's limited to the links in the home slider that point to documents and to the absolute links in the static pages.
We we're able to achieve this in the markdown pages thanks to glorious `remark-react` 🙌 . We provide a custom component for the `<a>` tags, and will use it to render all markdown links. This also allowed us to using `redux-first-router-link` `<Link />` for internal links.
Tested on transifex platform and the links are replaced by placeholders that need translating, so basically it _just works™_.
=> Feat: translate links

frontend/html/profile-place.ejs, frontend/scripts/react-components/profiles/scatterplot.component.jsx, frontend/styles/components/profiles/info.scss, frontend/styles/components/profiles/map.scss, frontend/styles/layouts/l-profile-actor.scss, frontend/styles/layouts/l-profile-place.scss
Following up https://github.com/Vizzuality/trase/issues/191. Minor styles changes, white outlines for maps, bringing up red dots to the front on scatterplots.
Printed examples:
- https://github.com/Vizzuality/trase/files/1894998/TRASE-1523369771420.pdf
- https://github.com/Vizzuality/trase/files/1894999/TRASE-1523369308027.pdf
=> profile pages: improving pdf a little bit

frontend/scripts/react-components/nav/filters-nav/recolor-by-selector/recolor-by-selector.component.jsx, frontend/scripts/react-components/nav/filters-nav/resize-by-selector/resize-by-selector.component.jsx, frontend/scripts/react-components/nav/filters-nav/years-selector/years-selector.container.js
OK so this PR makes sure, you can't select a year if the selected resize-by or recolor-by doesn't have data. I'm not a big fan of this, because limits what the user can do on the map (doesn't it?).
Please test and review.
=> feat: limit years based on resize by and recolor by

app/controllers/api/v3/download_controller.rb, app/services/api/v3/download/zipped_csv_download.rb, app/services/api/v3/download/zipped_download.rb, app/services/api/v3/download/zipped_json_download.rb, db/structure.sql
A few changes here:
- some new indexes on `download_flows_mv` to speed up filter by context and ordering of rows in downloads
- new column `row_name` in the `download_flows_mv`; this one used to be calculated on the fly for purposes of the pivot download, so having it pre-calculated should give it a boost and also can be used for sorting rows
- sorting is important, because we now added the chunking functionality to split files longer than 500k rows; this is done using `LIMIT` and `OFFSET` and it requires a predictable sort order
- my favourite part is giving the json downloads a boost by replacing the Rails `to_json` method with native Postgres json support. It makes the query take longer but there's almost no overhead on top of the query and the total time improvement is remarkable …
=> Download chunking

app/controllers/api/v3/nodes/nodes_attributes_controller.rb, app/services/api/v3/node_attributes/filter.rb, frontend/scripts/actions/tool.actions.js, frontend/scripts/components/tool/tool-content.component.js, frontend/scripts/containers/tool/titlebar.container.js, frontend/scripts/containers/tool/tool-content.container.js, frontend/scripts/reducers/helpers/getChoropleth.js, frontend/scripts/reducers/helpers/setNodesMeta.js, frontend/scripts/reducers/tool.reducer.js, spec/responses/api/v3/nodes_attributes_spec.rb, spec/services/api/v3/node_attributes/filter_spec.rb
Still WIP, and tests will probably fail. Will finish it next week
Loads map chorpeth info per selected layer(s) instead of loading the whole thing at once. Should improve perceived performance on initial load of the map/sankey
=> Load map nodes attributes per selected layer

frontend/scripts/react-components/shared/world-map/world-map.container.js
Fixing https://github.com/Vizzuality/trase/issues/462. Data shown on the map have a mismatch to the one in the table. The data was just taken from the wrong context (example Brazil-Beef 2014).
=> Explore page: fix world map data mismatch

app/admin/api/v3/map_attribute.rb
=> Fix labels for buckets in map attribute's active admin interface

frontend/scripts/react-components/nav/top-nav/global-search/global-search.component.jsx
Steps to reproduce
1. On home page search Cargill and click on Map link.
2. Go back to home page and open search. Previous search results are still visible because search state was not cleared.
=> reset search term when removing global search component

frontend/scripts/react-components/tool/tool.reducer.js
One-liner. Steps to reproduce the issue
1. Select any region on the map.
2. Use "Clear Selection" button - the region is still selected on the map.
=> Fix Tool: reset selection should clear selected nodes on the map

frontend/scripts/constants.js, frontend/scripts/pages/profile-actor.page.jsx, frontend/scripts/react-components/profiles/line.component.jsx, frontend/styles/_settings.scss, frontend/styles/components/profiles/line.scss, frontend/styles/layouts/l-profile-actor.scss, spec/support/schemas/importer_profile.json
This is for https://github.com/Vizzuality/trase/issues/385
I removed barely visible grey color from the palette (@juancarlosalonso please review)
On mobile view, as there is no map there and no reference to buckets, each line has different color - generated from the same color palette.
=> Profile: remove grey color from the palette, for mobile view each line different color

frontend/scripts/components/tool/map.component.js
This PR fixes one of the issues found desribed [here](https://basecamp.com/1756858/projects/12498794/todos/327056118) - the map size sometimes is not invalidated after CSS opening transistion. As we were giving [850ms for transisition to end](https://github.com/Vizzuality/trase/blob/develop/frontend/scripts/components/tool/map.component.js#L623), sometimes that was not enough. I was able to reproduce that most of the time doing following, from Home page search Sorriso Logistic Hub -> Click Supply Chain -> Go back to home -> find sorriso logistic hub -> Click Map.
=> Fix - map size sometimes not invalidated

app/services/api/v3/dashboards/filter_meta.rb
For contexts with national data country of origin comes from the context and this is not needed.
https://www.pivotaltracker.com/n/projects/1637931/stories/161288825
=> Remove COUNTRY OF PRODUCTION from the source tabs

frontend/scripts/react-components/shared/grid-list-item.component.jsx, frontend/scripts/react-components/shared/help-tooltip.component.jsx
This PR forces info window to render inside the modal when creating a dashboard.
https://www.pivotaltracker.com/story/show/161410221
=> fix info window

frontend/scripts/react-components/dashboard-element/dashboard-element.actions.js, frontend/scripts/react-components/dashboard-element/dashboard-element.reducer.js, frontend/scripts/react-components/dashboard-element/dashboard-element.saga.js, frontend/scripts/react-components/dashboard-element/dashboard-element.selectors.js, frontend/scripts/react-components/dashboard-element/dashboard-panel/dashboard-panel.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-panel/dashboard-panel.container.jsx, frontend/scripts/react-components/shared/grid-list.component.jsx
This PR refactors the `dashboard-panel.reducer`. I removed the adhoc variable names in favor of calling every item prop as `activeItem` and every tab prop as `activeTab`. Also extracted countries into a new panel, this is actually an abstract panel because there's no UI for it, but makes way more sense data wise.
I refactored some of the actions and components to fit to this new structure and removed a saga that set the first tab as active. Now instead of using a saga, we do this a reducer level. This solution seems more solid.
Finally the big WHY behind this refactor? I'm paving the road for my next PR that will search nodes across all tabs of the same panel and if a node is selected and doesn't belong to that tab, the tab will be changed.
Have fun 🌮
=> Fix: refactor dashboard panel reducer

frontend/scripts/react-components/profile-node/profile-node-widgets/top-destinations-widget.component.jsx, frontend/scripts/react-components/profiles/top-destinations-map.component.jsx
This PR fixes the profile pages choropleth tooltip. Before it was always showing the value for the first available year of data. Now it selected the one active page wide.
[Profile page map tooltips only displaying values for the top 5 countries shown on the line chart.](https://www.pivotaltracker.com/story/show/159235711)
=> fix: profiles choropleth map tooltip

frontend/scripts/react-components/nav/filters-nav/resize-by-selector/resize-by-selector.component.jsx
The logic behind the orderin was a little overcomplicated and had some unexpected behaviour in some browsers. This change ensures order is consistent.
[Resize by attribute "Group number" and "Position" field entries in CMS not translating to front end correctly](https://www.pivotaltracker.com/story/show/161918449)
=> fix resize by order

app/services/api/v3/download/flow_download_flat_query.rb, app/services/api/v3/download/flow_download_pivot_query.rb, app/services/api/v3/download/flow_download_query_builder.rb, app/services/api/v3/download/zipped_download.rb, spec/services/api/v3/download/flow_download_flat_query_spec.rb, spec/services/api/v3/download/flow_download_pivot_query_spec.rb, spec/services/api/v3/download/flow_download_query_builder_spec.rb, spec/services/api/v3/download/flow_download_spec.rb, spec/services/api/v3/download/zipped_csv_download_spec.rb, spec/services/api/v3/download/zipped_json_download_spec.rb, spec/support/helpers/zip_helpers.rb
The problem occurred when a pivot download became too long to fit in one file and needed to be chunked; the year condition was applied to the outer crosstab query where it resulted in a syntax error, a situation that we have no tests for. To fix this I encapsulated the flat query and the pivot query in their own objects, making it easier to control how the query is constructed when the year condition is applied, and added specs to cover those scenarios.
=> Fixed chunked pivot issue

frontend/scripts/actions/app.actions.js, frontend/scripts/react-components/nav/locale-selector/locale-selector.container.js, frontend/scripts/reducers/app.reducer.js, frontend/scripts/utils/stateURL.js
This PR fixes a bug where if you share an url with `lang=es` or any other locale that's not the default, the page would ignore the url locale and load the default one.
=> fix bug when landing on a translated page

frontend/scripts/react-components/profiles/dropdown-tab-switcher.component.jsx, frontend/scripts/react-components/profiles/line.component.jsx
This PR fixes a crash on mobile profile pages due to a broken event handler.
=> fix: dropdown tab switcher handler crash

frontend/styles/components/profiles/area-table.scss
Fixes text overflowing to a second line on profile-pages tables.
[Profile pages: Scale on water scarcity is incorrect. Should be '/7'](https://www.pivotaltracker.com/story/show/161919472)
=> fixes styles for table score units

frontend/scripts/react-components/profiles/line.component.jsx
This PR addresses an issue where long named nodes got cut on the line charts label.
[On actor profiles, long place names of the top destination and top sourcing tables are being cut off in the legend](https://www.pivotaltracker.com/story/show/162156663)
=> fix: line chart labels get cut

config/environments/sandbox.rb, config/initializers/assets.rb
- turns off asset compilation for sandbox (like for production)
- adds active admin assets to list of precompiled assets
=> Precompile Active Admin assets

Capfile
This requires changing apache's settings to have it serve the assets folder directly, instead of passing it to passenger for rails to handle
=> Add asset precompilation to capistrano deploy workflow

.gitignore, app/controllers/api/v3/download_controller.rb, app/models/api/v3/readonly/base_model.rb, app/models/api/v3/readonly/download_flow.rb, app/serializers/api/v3/download_attribute_serializer.rb, app/services/api/v3/download/flow_download.rb, app/services/api/v3/download/parameters.rb, app/services/api/v3/download/precomputed_download.rb, app/services/api/v3/download/zipped_download.rb, app/workers/precomputed_download_refresh_worker.rb, config/deploy.rb, lib/tasks/downloads.rake, lib/zipfile.rb, spec/controllers/api/v3/download_controller_spec.rb, spec/services/api/v3/download/flow_download_flat_query_spec.rb, spec/services/api/v3/download/flow_download_pivot_query_spec.rb, spec/services/api/v3/download/flow_download_query_builder_spec.rb, spec/services/api/v3/download/flow_download_spec.rb, spec/services/api/v3/download/zipped_csv_download_spec.rb, spec/services/api/v3/download/zipped_json_download_spec.rb, spec/workers/database_update_worker_spec.rb
Modification of the download service so that in case of full downloads it first checks if a file is already generated and serves that; in case it's not, after generating it it stores it for future use.
After the download flows materialised view refreshes, it precomputes all full pivot csv downloads.
There are capistrano tasks:
`cap [env] downloads:clear`
`cap [env] downloads:refresh` <- this one clears immediately and refreshes in background after `sidekiq:restart`
=> Pre-computed downloads

app/models/api/v3/readonly/download_flow.rb, db/migrate/20190111121850_update_download_flows_mv_to_handle_new_zd_values.rb, db/structure.sql, db/views/download_flows_mv_v04.sql
When this was first built, the values of ZERO_DEFORESTATION were either "yes" or "no", so the conversion to boolean worked great (the reason for the conversion was that values need to be aggregated, and that worked well with booleans). Now that the value can be any text, I needed to remove the conversion and have the textual values displayed as is, with string aggregation in case of conflicting values.
=> Display ZERO_DEFORESTATION as text, rather than convert to boolean

app/models/api/v3/flow.rb, app/services/api/v3/database_validation/chain_builders/download_attribute_chain_builder.rb, app/services/api/v3/database_validation/chain_builders/map_attribute_chain_builder.rb, app/services/api/v3/database_validation/chain_builders/recolor_by_attribute_chain_builder.rb, app/services/api/v3/database_validation/chain_builders/resize_by_attribute_chain_builder.rb, app/services/api/v3/database_validation/checks/declared_years_match_flow_attributes.rb, app/services/api/v3/database_validation/checks/declared_years_match_node_attributes.rb, spec/services/api/v3/database_validation/checks/declared_years_match_flow_attributes_spec.rb, spec/services/api/v3/database_validation/checks/declared_years_match_node_attributes_spec.rb, spec/support/contexts/api/v3/minimum_complete_configuration.rb
Separate validation logic needed for map attributes, looking for temporal data in node attributes rather than flow attributes.
Some background: This is part of a custom data validation system we built to validate the dataset after importing new data. It's different from regular ActiveRecord validations in that they don't run on record creation; in terms of the core dataset, records are not created one by one but the contents of the entire table is replaced during a data update process. The validation system codifies some data consistency rules to validate the new dataset.
There is a particular validation rule which was applied to a few similarly structured tables. `download_attributes`, `recolor_by_attributes`, `resize_by_attributes` and `map_attributes` all have a `years` column, which …
=> Validate declared years for map attributes using node attributes values

app/services/api/v3/database_validation/chain_builders/context_chain_builder.rb, app/services/api/v3/database_validation/checks/path_matches_context_node_types.rb, db/migrate/20190110094614_add_length_restriction_to_flow_path.rb, db/structure.sql, spec/factories/api/v3/api_v3_flows.rb, spec/services/api/v3/database_validation/checks/path_matches_context_node_types_spec.rb, spec/support/contexts/api/v3/minimum_complete_configuration.rb
https://www.pivotaltracker.com/story/show/162124214
https://github.com/Vizzuality/trase/issues/551
This adds a new validation to help with issues resulting from incorrect structure of flow paths. The `flows` table describes the path through which a particular commodity travelled. It is a denormalized table, where the `path` column is an array of node ids. The length of that array depends on the context and should match the number of records in `context_node_types`. For practical reason the path should never be shorter than 4 nodes (because otherwise we cannot render the sankey correctly).
This PR adds
* a `CHECK` constraint on the flows path to ensure it is never shorter than 4 nodes. Adding this as a constraint on the database will crash the import process early.
* a validation that …
=> Validate paths length matches context node types and is minimum 4 nodes

app/services/api/v3/database_validation/chain_builders/context_chain_builder.rb, app/services/api/v3/database_validation/checks/path_length_matches_context_node_types.rb, app/services/api/v3/database_validation/checks/path_positions_match_context_node_types.rb, app/services/concerns/api/v3/database_validation/checks/error_message_with_violating_flows.rb, spec/services/api/v3/database_validation/checks/path_length_matches_context_node_types_spec.rb, spec/services/api/v3/database_validation/checks/path_positions_match_context_node_types_spec.rb
https://github.com/Vizzuality/trase/issues/540
This adds a new validation, which again has to do with flow paths. This one checks that the node ids on respective path positions correspond to records in the `context_node_types` table. For example, for Brazil-soy context the node in first position should be a BIOME. To check for offenders it runs a query which normalizes flows (by `UNNEST`ing the paths with `ORDINALITY` to get the actual positions), gets the actual node types and positions and cross checks that with expected node types on these positions from `context_node_types`, looking for mismatched flows.
=> Validate that column positions in flow paths match context_node_types

frontend/html/tool.ejs, frontend/scripts/react-components/shared/dropdown.component.jsx, frontend/scripts/react-components/shared/sentence-selector/sentence-selector.container.js, frontend/scripts/react-components/shared/sentence-selector/sentence-selector.scss, frontend/styles/_settings.scss, frontend/styles/components/shared/dropdown.scss, frontend/styles/layouts/l-tool.scss
This PR addresses the following two issues:
- User can't really tell that there's mote options available in a dropdown. Now we purposely show only the half of last item.
- Clear nodes button in `/flows` page footer bar was broken. Fixes regression.
=> Fix: minor ui fixes

frontend/scripts/react-components/profile-node/profile-node-widgets/importing-companies-widget.component.jsx, frontend/scripts/react-components/profiles/dropdown-tab-switcher/dropdown-tab-switcher.component.jsx, frontend/scripts/react-components/profiles/scatterplot/scatterplot.component.jsx, frontend/scripts/react-components/profiles/top-destinations-chart.component.jsx, frontend/styles/layouts/l-profile-actor.scss
This PR hides the scatterplot and the tab switcher when there's no data.
=> Feat: hide empty profile widgets

frontend/scripts/react-components/dashboard-element/dashboard-element.fetch.saga.js, frontend/scripts/react-components/dashboard-element/dashboard-element.reducer.js, frontend/scripts/react-components/dashboard-element/dashboard-panel/dashboard-panel.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-panel/dashboard-panel.container.jsx, frontend/scripts/react-components/dashboard-element/dashboard-panel/sources-panel.component.jsx, frontend/scripts/react-components/shared/tags-group/tags-group.component.jsx, frontend/scripts/tests/dashboard-element/reducer.test.js
This PR address a couple of issues I found on the sources panel:
- Search in sources should show only countries when no country is selected. If you selected a country, then deselect it and search again, the results were not showing countries but jurisdictions.
- When changing tab using the search, the page number wasn't being reset.
- When changing tabs the data being reset was that of the new tab, instead of the previous.
=> fix: showing incorrect results + clearing wrong tab data

app/services/api/v3/dashboards/chart_data_from_flow_attributes.rb, app/services/api/v3/dashboards/retrieve_attributes.rb, spec/controllers/api/v3/dashboards/chart_data_controller_spec.rb, spec/controllers/api/v3/dashboards/companies_controller_spec.rb, spec/controllers/api/v3/dashboards/destinations_controller_spec.rb, spec/support/contexts/api/v3/brazil/brazil_flows.rb, spec/support/contexts/api/v3/brazil/brazil_flows_quants.rb
* Fix filtering in the dashboards/chart_data endpoint - use OR operator instead of AND for filtering companies_ids
* Fix filtering in the dashboards/attributes endpoint - use OR operator instead of AND for filtering companies_ids
* Solution: replace ARR1 @> ARR2 operator that checks for EVERY element from ARR2 in ARR1 with && operator checking if the they have ANY elements in common
PT task:
https://www.pivotaltracker.com/n/projects/1637931/stories/164108523
And also:
https://www.pivotaltracker.com/n/projects/1637931/stories/164108677
https://www.pivotaltracker.com/n/projects/1637931/stories/164109281
As the `nodes_ids` in `RetrieveAttributes` service include all `companies_ids`, `destinations_ids` and `sources_ids`.
Testing:
Check …
=> [BE] Fix selecting multiple companies

app/models/api/v3/chart_ind.rb, app/models/api/v3/chart_qual.rb, app/models/api/v3/chart_quant.rb, app/models/api/v3/readonly/download_flow.rb, app/services/api/v3/import/importer.rb, app/services/api/v3/import/mirror_import.rb
A few things:
- delete the temporary schema used for importing data as soon as possible to reduce spike in disk usage
- while materialized views should be refreshed synchronously as part of the process, precomputed downloads can be generated asynchronously after the upload is finished
- finally, there was a stupid mistake because of which chart attributes would get lost after update
=> Sorting out a few things in the data uploader

frontend/scripts/react-components/dashboard-element/dashboard-element.reducer.js, frontend/scripts/react-components/dashboard-element/dashboard-element.saga.js, frontend/scripts/tests/dashboard-element/reducer.test.js, frontend/scripts/tests/dashboard-element/saga.test.js, frontend/scripts/tests/utils/record-saga.js
So I finally tackled the annoying situation where changing panels would cause data reload even if nothing had actually changed. The solution is pretty cool, I'm using `redux-saga's take()` effect to calculate the changes between panel changes 😏 .
Besides that, I discovered another bug on the tabs selection:
1. Fetch new tabs according to selection change.
2. If a selected tab existed prior to tabs fetch, use it as default, otherwise use `tabs[0]`.
Problem? We weren't checking if the selected tab also existed in the new tabs, leaving an invalid selection as default.
1. Fetch new tabs according to selection change.
2. If a selected tab existed prior to tabs fetch and exists in new tabs, use it as default, otherwise use `tabs[0]`.
Another issue that is fixed here:
When selecting and …
=> Fix: prevent dashboards unnecessary fetch

app/services/api/v3/actors/top_nodes_summary.rb, spec/responses/api/v3/exporter_profile_spec.rb, spec/responses/api/v3/importer_profile_spec.rb, spec/support/schemas/v3_actor_top_sources.json
Fixes https://www.pivotaltracker.com/story/show/164576161
The problem was due to "unknown" municipalities in the flow path. This is an example of the top sources chart which illustrates what happens:
top states:
top municipalities:
In year 2003 there is a dot present on the state chart for Rio grande do sul, but no data on the municipality chart. This is because the municipalities involved in the 2003 flows are "unknown" (only state is known), and so were filtered out from the chart. That caused an exception when retrieving municipality data for 2003.
=> Fixes exception when unknown nodes present

app/models/api/v3/ind_commodity_property.rb, app/models/api/v3/ind_context_property.rb, app/models/api/v3/ind_country_property.rb, app/models/api/v3/qual_commodity_property.rb, app/models/api/v3/qual_context_property.rb, app/models/api/v3/qual_country_property.rb, app/models/api/v3/quant_commodity_property.rb, app/models/api/v3/quant_context_property.rb, app/models/api/v3/quant_country_property.rb, app/models/api/v3/readonly/commodity_attribute_property.rb, app/models/api/v3/readonly/context_attribute_property.rb, app/models/api/v3/readonly/country_attribute_property.rb, db/migrate/20190320122547_remove_uniqueness_id_constraint_from_m_vs.rb, db/structure.sql
Remove all unique indexes from context/commodity/country attributes properties materialized views (uniqueness only on `:id` which was causing an error -> https://www.pivotaltracker.com/n/projects/1637931/stories/164764230) and instead add uniqueness keys on more than one column.
=> Fix uniqueness on materialized views

app/admin/api/v3/ind_commodity_property.rb, app/admin/api/v3/ind_context_property.rb, app/admin/api/v3/ind_country_property.rb, app/admin/api/v3/qual_commodity_property.rb, app/admin/api/v3/qual_context_property.rb, app/admin/api/v3/qual_country_property.rb, app/admin/api/v3/quant_commodity_property.rb, app/admin/api/v3/quant_context_property.rb, app/admin/api/v3/quant_country_property.rb, app/models/api/v3/readonly/commodity_attribute_property.rb, app/models/api/v3/readonly/context_attribute_property.rb, app/models/api/v3/readonly/country_attribute_property.rb, db/migrate/20190321122822_add_unique_indexes_on_materialized_views.rb, db/structure.sql, spec/controllers/admin/ind_commodity_properties_controller_spec.rb, spec/controllers/admin/ind_context_properties_controller_spec.rb, spec/controllers/admin/ind_country_properties_controller_spec.rb, spec/controllers/admin/qual_commodity_properties_controller_spec.rb, spec/controllers/admin/qual_context_properties_controller_spec.rb, spec/controllers/admin/qual_country_properties_controller_spec.rb, spec/controllers/admin/quant_commodity_properties_controller_spec.rb, spec/controllers/admin/quant_context_properties_controller_spec.rb, spec/controllers/admin/quant_country_properties_controller_spec.rb
- Another attempt to fix indexes on materialized views
- Display user-friendly names of quals/inds/quants on controller#show action in admin panel for context/commodity/country qual/inds/quants properties. Also, for context-specific attributes, instead of showing context's id in the show page, show commodity and country names as it's more readable.
=> Unique indexes on materialized views

app/services/api/v3/dashboards/parametrised_charts.rb, config/routes.rb, spec/services/api/v3/dashboards/parametrised_charts_spec.rb
This doesn't add a new endpoint - reuses the same endpoint as for the "overview". The difference is in how the endpoint is filtered, the idea being these charts only make sense when flow any path filters are selected.
=> Multi year, ncont, node type view (stacked bar chart)

app/models/api/v3/context_node_type_property.rb, app/models/api/v3/readonly/dashboards/country.rb, app/models/api/v3/readonly/dashboards/flow_path.rb, app/services/api/v3/dashboards/filter_meta.rb, db/migrate/20190321161913_update_dashboards_flow_paths_mv.rb, db/structure.sql, db/views/dashboards_companies_mv_v04.sql, db/views/dashboards_destinations_mv_v04.sql, db/views/dashboards_flow_paths_mv_v03.sql, db/views/dashboards_sources_mv_v04.sql, spec/factories/api/v3/api_v3_context_node_type_properties.rb, spec/services/api/v3/dashboards/node_types_to_break_by_spec.rb, spec/support/contexts/api/v3/brazil/brazil_beef_context_node_types.rb, spec/support/contexts/api/v3/brazil/brazil_context_node_types.rb, spec/support/contexts/api/v3/paraguay/paraguay_context_node_types.rb
This PR applies a new **role** attribute from _context_node_type_properties_ to dependent materialized views.
I also updated the specs although two of them are still failing; one has something to do with populating materialized views and the other returns one more company than before - @agnessa could you steer me in the right direction what may be going on in here?
=> Apply node type role attribute to dashboards filters

app/services/api/v3/dashboards/charts/multi_year_ncont_overview.rb, app/services/api/v3/dashboards/charts/multi_year_no_ncont_node_type_view.rb, app/services/api/v3/dashboards/charts/multi_year_no_ncont_overview.rb, app/services/api/v3/dashboards/charts/single_year_ncont_node_type_view.rb, app/services/api/v3/dashboards/charts/single_year_ncont_overview.rb, app/services/api/v3/dashboards/charts/single_year_no_ncont_node_type_view.rb, app/services/api/v3/dashboards/charts/single_year_no_ncont_overview.rb, app/services/concerns/api/v3/dashboards/charts/helpers.rb
Add additional info to `meta` key in dashboard charts endpoints of this structure:
```
meta: {
...,
info: {
node_type: @node_type&.name,
years: {
start_year: @start_year || @year,
end_year: @end_year
},
top_n: @top_n,
filter: {
cont_attribute: @cont_attribute&.display_name,
ncont_attribute: @ncont_attribute&.display_name
}
}
```
If for any of the properties value is not existent it will return `null`. Note, that also for `single_year..` endpoints the year is nested in `years.start_year`
The change affects these endpoints:
`api/v3/dashboards/charts/single_year_no_ncont_overview`
`api/v3/dashboards/charts/single_year_ncont_overview`
`api/v3/dashboards/charts/single_year_no_ncont_node_type_view`
`api/v3/dashboards/charts/single_year_ncont_node_type_view` …
=> Add additional meta info to dashboard charts endpoints

frontend/scripts/react-components/dashboard-element/dashboard-element.actions.js, frontend/scripts/react-components/dashboard-element/dashboard-element.fetch.saga.js, frontend/scripts/react-components/dashboard-element/dashboard-element.reducer.js, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.container.jsx, frontend/scripts/tests/dashboard-element/reducer.test.js, frontend/scripts/tests/dashboard-element/saga.test.js, frontend/scripts/tests/dashboard-widget/__snapshots__/dashboard-widget-selectors.test.js.snap
This PR fixes the broken snapshot tests and prevents sets the widgets to loading when a indicator has changed. It also prevents spinners from showing if there's no need for them to show.
=> Fix: dashboard loading spinners

spec/services/api/v3/dashboards/charts/single_year_ncont_overview_spec.rb
This spec used to depend on the order of data returned in the response, which is not guaranteed.
=> Fix spec depending on order of data

frontend/.babelrc, frontend/config/webpack.config.js, frontend/package.json, frontend/scripts/index.js, frontend/yarn.lock
Adds missing config and updates babel transform-runtime.
This is a polyfill change, could you test it on browserstack 🙏 .
I tested in Chrome, FF and Safari, but prefer to be sure.
=> Fix corejs2 to corejs3 migration

app/controllers/concerns/api/v3/dashboards/filter_params.rb, app/services/api/v3/dashboards/chart_parameters.rb, app/services/api/v3/dashboards/charts/multi_year_no_ncont_node_type_view.rb, app/services/api/v3/dashboards/charts/single_year_ncont_node_type_view.rb, app/services/api/v3/dashboards/charts/single_year_no_ncont_node_type_view.rb, app/services/api/v3/dashboards/node_types_to_break_by.rb, app/services/api/v3/dashboards/parametrised_charts.rb, app/services/concerns/api/v3/dashboards/charts/helpers.rb, doc/swagger.yaml, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.container.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.selectors.js, spec/controllers/api/v3/dashboards/sources_controller_spec.rb, spec/services/api/v3/dashboards/node_types_to_break_by_spec.rb, spec/services/api/v3/dashboards/parametrised_charts_spec.rb, spec/support/contexts/api/v3/brazil/brazil_context_node_types.rb
https://www.pivotaltracker.com/story/show/165237654
- overview chart filtered by all flow path filters
- "single node view" charts filtered by 1 node from a category + remaining selection, for example: when 2 sources and one destination selected, that generates 3 charts of this type:
1. chart for source1 filtered by source1 and destination
2. chart for source2 filtered by source2 and destination
3. chart for destination, filtered by destination and both sources
- adds missing "break by top nodes" charts
- adds a new `single_filter_key` property, with the value of one of `sources, companies, destinations` - telling you in which of the arrays under `filter` the selected node is
The below screenshot shows the charts generated for multiple years, ncont indicator, 2 sources, 1 destination, …
=> Fixes to multi-year ncont scenario

app/services/api/v3/dashboards/charts/multi_year_no_ncont_node_type_view.rb, app/services/api/v3/dashboards/charts/single_year_ncont_node_type_view.rb, app/services/api/v3/dashboards/charts/single_year_no_ncont_node_type_view.rb, app/services/concerns/api/v3/dashboards/charts/helpers.rb
Adds profile information to allow displaying links to profile pages. Where the info is depends on type of chart.
- dynamic sentence, or any kind of dynamic title, which incorporates information about current filters: use meta -> info -> filter -> [sources | companies]
- horizontal bar chart (single year, no ncont and ncont) - to display axis labels as links, use meta -> yLabelsProfileInfo. It's an array of elements corresponding to data, e.g.
```
"data":[  
{  
"y":"DOMESTIC CONSUMPTION",
"x0":58.408964958192
},
{  
"y":"GRANOL",
"x0":15.4620350246747
}
]
```
```
"yLabelsProfileInfo":[  
{  
"id":3,
"profile":"actor"
},
{  
"id":27717,
"profile":"actor"
}
],
```
- stacked bar chart (multi year, no ncont and ncont) - use meta -> yn -> profileInfo, e.g.
```
"y0":{  
"label":"ADAMANTINA", …
```
=> Add profile info to axis labels and legend

frontend/scripts/router/router.js
Use a middleware to add the current Language to url when we switch pages. Its in the after change as in the before change we still not have the variable.
The default is 'en' and we can't use Transifex as its not loading in this hook
=> Use a middleware to add the current Language to url when we switch pages

frontend/scripts/react-components/dashboard-element/dashboard-widget/table-modal/table-modal.selectors.js, frontend/scripts/react-components/dashboard-element/dashboard-widget/table-modal/table/table.component.jsx
This tiny PR fixes a problem in the table of the ranking chart (and probably many others) where we had some isNANUndefined showing. We needed to update the blacklist of data column names. This could be improved in the future so we don't have this problem again.
Try: Brasil - Soy ... open table with the table button
Before:
=> update data column names and avoid future isNaNs

app/services/api/v3/dashboards/charts/multi_year_ncont_overview.rb, app/services/api/v3/dashboards/charts/multi_year_no_ncont_node_type_view.rb, app/services/api/v3/dashboards/charts/single_year_ncont_node_type_view.rb, app/services/concerns/api/v3/dashboards/charts/helpers.rb, doc/swagger.yaml
Applies to multi year ncont overview, multi year no ncont node type view, single year ncont node type view.
Issue mentioned in https://github.com/Vizzuality/trase/pull/794
=> Added axis unit to series legends for stacked bar charts

app/serializers/api/v3/profile_metadata/profile_serializer.rb
Serializer needs to be specified explicitly, otherwise a generic serializer is used and the virtual attribute `chart_type` is not serialized.
=> Works fine in development, on sandbox cannot find the serializer ¯\_(ツ)_/¯

frontend/scripts/react-components/chart/chart.component.jsx, frontend/scripts/react-components/chart/tick/category-tick.component.jsx, frontend/scripts/react-components/chart/y-axis.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-element.selectors.js, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.selectors.js, frontend/scripts/react-components/dashboard-element/dashboard-widget/dynamic-sentence-widget/dynamic-sentence-widget.selectors.js, frontend/scripts/react-components/dashboard-element/dashboard-widget/ranking-widget/ranking-widget-styles.scss, frontend/scripts/react-components/dashboard-element/dashboard-widget/ranking-widget/ranking-widget.component.jsx, frontend/scripts/react-components/shared/tags-group/tag/tag.component.jsx, frontend/scripts/tests/dashboard-widget/__snapshots__/dashboard-widget-selectors.test.js.snap
This PR fixes the link to profiles in the ranking chart. It should only appear if the profile property inside `yLabelsProfileInfo` is not null.
Other miscellaneous fixes:
- Don't pass non chart data through config. I think config should only describe how the chart actually looks like, passing stuff like info or meta feels wrong.
- Translate ignored strings using imperative method: `translateText`.
- Improve _just a bit_ the logo flashing on home page (it was driving me crazy).
- Add missing total value in ranking charts and limit the number of lines the ranking chart elements occupy.
=> Fix ranking links to profiles

frontend/scripts/index.ejs
There's a crash when the Transifex script loads before the JS bundle.
=> fix onTransifexLoad not defined

frontend/scripts/react-components/shared/footer/footer.component.jsx, frontend/scripts/router/nav-links.js
This simple PR adds privacy and cookie pages to the about page and privacy link to the footer.
Note: The privacy markdown should contain a link to the cookie page
AT:
=> Add pages in about and privacy link on footer

frontend/scripts/actions/app.actions.js, frontend/scripts/analytics/tool.events.js, frontend/scripts/react-components/dashboard-element/dashboard-element.fetch.saga.js, frontend/scripts/react-components/nav/filters-nav/filters-nav.container.js, frontend/scripts/react-components/nav/filters-nav/recolor-by-selector/recolor-by-selector.js, frontend/scripts/react-components/tool-layers/tool-layers.reducer.js, frontend/scripts/react-components/tool-links/tool-links.actions.js, frontend/scripts/react-components/tool-links/tool-links.fetch.saga.js, frontend/scripts/react-components/tool-links/tool-links.reducer.js, frontend/scripts/react-components/tool-links/tool-links.saga.js, frontend/scripts/react-components/tool/column-selector/column-selector.container.jsx, frontend/scripts/react-components/tool/map-basemaps/map-basemaps.container.js, frontend/scripts/react-components/tool/map-context/map-context.container.js, frontend/scripts/react-components/tool/map-dimensions/map-dimensions.container.js, frontend/scripts/react-components/tool/map/map.component.js, frontend/scripts/react-components/tool/map/map.container.js, frontend/scripts/react-components/tool/nodes-titles/nodes-titles.container.js, frontend/scripts/react-components/tool/sankey/sankey.container.js, frontend/scripts/react-components/tool/tool-content/tool-content.container.js, frontend/scripts/react-components/tool/tool-search/node-title-group/node-title-group.container.js, frontend/scripts/react-components/tool/tool-search/tool-search.container.js, frontend/scripts/react-components/tool/tool.actions.js, frontend/scripts/react-components/tool/tool.thunks.js, frontend/scripts/reducers/app.reducer.js, frontend/scripts/sagas.js, frontend/scripts/tests/dashboard-element/fetch.saga.test.js, frontend/scripts/tests/dashboard-element/saga.test.js, frontend/scripts/utils/saga-utils.js
This PR moves some things around to start fetch data with sagas. I was able to remove an imperative call to update the fetching when context switches. Now we listen to the `SET_CONTEXT` action and fetch the data.
=> Feat: use sagas to load nodes columns

frontend/html/tool.ejs, frontend/scripts/constants.js, frontend/scripts/router/router.js, frontend/styles/components/shared/modal.scss
We are going to use the non-supported page for all non desktop pages
=> Replace modal with non supported page for non desktop pages

app/admin/api/v3/context.rb, app/admin/api/v3/top_profile.rb, app/models/api/v3/context.rb, app/models/api/v3/node.rb, app/models/api/v3/readonly/node.rb, app/models/api/v3/top_profile.rb, app/services/api/v3/import/tables.rb, db/migrate/20190618131945_create_top_profiles.rb, db/structure.sql, spec/controllers/admin/contexts_controller_spec.rb, spec/controllers/admin/top_profiles_controller_spec.rb, spec/factories/api/v3/api_v3_top_profile.rb
PT task: https://www.pivotaltracker.com/n/projects/1637931/stories/166730157
* Add top_profiles table to the DB: associations with context and node
* Add associations to context and node models
* Add CMS pages for context and top profiles
* Filter available nodes for top profiles
1. New `Contexts` tab in the CMS (it's not nested)
2. Index page show dot-listed contexts with links to the details about a single context (looks like `Dashboard` index)
3. Context details include a link to `Top Profiles`
4. Top Profiles are listed for that specific context
5. Add page for Top Profile is filtering the available nodes (these which have profile pages defined in that context)
6. I used materialized views, turned off the filters in the CMS and used scoped collection in the `Context` for performance …
=> Allow managing Top Profiles in the CMS

app/models/api/v3/context_node_type_property.rb
sankey_nodes_mv needs to be refreshed following an update to context_node_type_properties
=> Refreshing sankey_nodes_mv

app/services/api/v3/places/indicators_table.rb
Values of quals now loaded in initialiser, so that lack of STATE qual does not prevent other quals being preloaded
=> Preload quals early in profile pages

app/admin/api/v3/top_profile.rb, app/services/api/v3/top_profiles/derive_top_profile_details.rb, spec/controllers/admin/top_profiles_controller_spec.rb, spec/services/api/v3/top_profiles/derive_top_profile_details_spec.rb
PT task: https://www.pivotaltracker.com/story/show/167063535
Top Profiles: Return last available year of data per node and not per context. Use `nodes_mv` for that purpose.
=> Top Profiles: Return last available year of data per node

app/models/api/v3/top_profile_image.rb
Changed behaviour from destroying linked top profiles to just nullifying the image.
=> Do not destroy top profiles when image destroyed

app/serializers/api/v3/top_profiles_serializer.rb, app/services/api/v3/top_profiles/get_matching_image.rb
PT task: https://www.pivotaltracker.com/story/show/167162476
Added a service `GetMatchingImage` that first tries to find matching top profile images (same **commodity** and **profile_type**) - if it doesn't find anything, returns `nil`. We could have some predefined images for that if it's not a desired behaviour. Let me know in the comment.
If it has some matching images then it tries to find the ones that are not assigned to any top profile; if it does, it returns a random one, if not, it returns a random one from the matching images.
Everything happens on the fly, so there are no assignments in the DB. If we want to persist that, let me know in the comments as well.
=> Get random matching img for top profile

frontend/scripts/react-components/nav/filters-nav/filters-nav.selectors.js, frontend/scripts/react-components/shared/recolor-by/recolor-by.component.jsx, frontend/scripts/react-components/tool-links/tool-links.selectors.js, frontend/scripts/react-components/tool/sankey/sankey.d3layout.js, frontend/scripts/react-components/tool/sankey/sankey.utils.js, frontend/scripts/react-components/tool/sankey/sort-flows.js, frontend/scripts/reducers/helpers/mergeLinks.js, frontend/scripts/tests/tool/sankey/sort-flows.test.js
This PR fixes a regression where nodes after selection werent splitted like they should.
**Related pivotal task:** https://www.pivotaltracker.com/story/show/167195012
Also fixes the imfamous links sorting issue, where links didnt follow their original order across columns:
> the ordering of colors is different for incoming and outgoing flows, which breaks the continuity and defeats the purpose of using a flow diagram.
See before and after for links ordering solution:
**Before**
**After**
=> Fix: sankey flows merge

app/services/api/v3/dashboards/charts/multi_year_no_ncont_node_type_view.rb
PT task: https://www.pivotaltracker.com/story/show/167065042
For selected nodes don't include `OTHER` in the legend.
Before:
After:
Note that on the attached second screen we're displaying `OTHER` in the legend of `Top 10 Importers` because no importer was selected before.
To test this scenario:
First pick `Brazil`, then from optional regions: `Brasnorte` and `Campos de Julio` --> `SOY` --> nothing --> from exporters tab `Bunge` and `Amaggi`
=> In comparison view dont include other in legend

config/sitemap.rb, public/robots.txt
The default host of the sitemap urls was pointing to the http protocol and not https
=> Update default host

frontend/scripts/react-components/profiles/top-destinations-chart.component.jsx, frontend/scripts/react-components/shared/world-map/world-map.component.jsx, frontend/scripts/utils/isMobile.js
Disable tooltips for mobile in explore component. This was made for mobile UX reasons, the size of the action tooltips was too little. Maybe in the future would be nice to have some list with the countries
Also, checking the size of the breakpoint I realise that this doesn't fit most of the mobile width. We shall review this breakpoints.
=> Disable interaction for mobile in explore

frontend/scripts/constants.js, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.selectors.js
This PR adds a different title to the widgets that are filtered by nodes and don't show anymore the top N nodes:
This works in:  IMPORTER,  EXPORTER, BIOME,  STATE, MUNICIPALITY, and COUNTRY.
Maybe the top N chart will still be relevant so we might want to add it in other iteration.
Try:
1. Go to dashboard.
2. Select Cofco and Bunge as exporters.
3. Go to top 10 exporters chart.
4. It's only showing 2 exporters.
=> Add comparison title to charts with compared nodes

app/services/api/v3/dashboards/base_filter.rb, spec/services/api/v3/dashboards/filter_sources_spec.rb
https://www.pivotaltracker.com/story/show/167809756
The problem: you want to be able to filter nodes in the dashboards filtering panel by nodes selected on a different tab of the same panel, e.g. you select a biome on first tab and then go to municipalities tab. The reason this wasn't working before is because the node ids belonging to the category of the panel are treated differently than those passed as filters from different panels, which, when combined with the node type filter, produced an empty result. For example:
/sources?node_type_id=[id of municipality]&sources_ids=[id of a biome] - this would look for nodes with node type matching municipality and id matching the specified biome
The solution:  If the parameters include both node ids from same role, e.g. sources_ids sent to …
=> Allow filtering by nodes with same role and different node type in dashboards filter

app/models/api/v3/download_attribute.rb
download_flows should only be refreshed once during data import, and not from CMS callbacks; this was a leftover from a previous solution
=> Removed instruction to refresh download_flows

config/application.rb
Instructs pg_dump to omit download_flows partitions in structure.sql.
=> Instruct pg_dump to ignore table partitions

frontend/scripts/react-components/tool-links/tool-links.actions.js, frontend/scripts/react-components/tool-links/tool-links.fetch.saga.js, frontend/scripts/react-components/tool-links/tool-links.reducer.js, frontend/scripts/react-components/tool-links/tool-links.saga.js
The problem was that when changing context we called `getToolGeoColumnNodes` without `replaceData` and then we called `getToolNodesByLink` with `replaceData`. This effectively deleted the previously downloaded geoColumn nodes and added the rest of the nodes. The sankey worked without crashing due to selectors memoization.
=> fix sankey geocolumn not loading

frontend/scripts/react-components/dashboard-element/dashboard-element.fetch.saga.js, frontend/scripts/react-components/dashboard-element/dashboard-element.reducer.js, frontend/scripts/react-components/dashboard-element/dashboard-element.saga.js, frontend/scripts/react-components/dashboard-element/dashboard-element.selectors.js, frontend/scripts/react-components/dashboard-element/dashboard-panel/companies-panel.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-panel/destinations-panel.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-panel/sources-panel.component.jsx, frontend/scripts/react-components/shared/grid-list/grid-list.component.jsx, frontend/scripts/react-components/shared/grid-list/grid-list.hooks.js, frontend/scripts/react-components/shared/profile-selector/profile-panel/profile-panel.fetch.saga.js, frontend/scripts/react-components/shared/profile-selector/profile-panel/profile-step-panel/profiles-companies-panel.component.jsx, frontend/scripts/react-components/shared/profile-selector/profile-panel/profile-step-panel/profiles-sources-panel.component.jsx, frontend/scripts/react-components/shared/profile-selector/profile-selector.reducer.js
I removed the jump ahead feature and fixed some bugs that surfaced while doing so.
1. We we're resetting the page to the initial state every time we selected an item through the search bar. This made it impossible to load the following items.
2. We were requesting the sources in the url when landing on the app, this failed when the user hadn't selected a commodity because we didnt have a context id yet. Now, we dont serialise the sources until we have selected a country and a commodity.
=> fixes jump when scrolling of gridlist

app/services/api/v3/flows/filter.rb, spec/services/api/v3/flows/filter_spec.rb
https://www.pivotaltracker.com/story/show/168238572
It's an interesting bug; recently we refactored the flows service slightly to allow passing resize / recolor attributes by attribute id, and as part of that we slightly modified the flows query, which caused the bug.
These 2 queries are not equivalent:
SELECT flows.id,ARRAY[flows.path[3], flows.path[6], flows.path[7], flows.path[8]] AS path,
flow_quants.value AS quant_value,flow_inds.value::DOUBLE PRECISION AS ind_value, NULL::TEXT AS qual_value 
FROM "flows"
INNER JOIN "flow_quants" ON "flow_quants"."flow_id" = "flows"."id" 
LEFT JOIN flow_inds ON flow_inds.flow_id = flows.id 
WHERE "flows"."context_id" = 1
AND (year >= '2017' AND year <= '2017')
AND "flow_quants"."quant_id" = 1
AND (flow_quants.value > 0) **AND "flow_inds"."ind_id" = …
=> Fixed join condition for recolour by flow values

app/services/api/v3/places/basic_attributes.rb
Returning pasture_area in the new header_attributes format
=> Fix pasture area format

app/controllers/api/v3/profile_metadata_controller.rb, app/serializers/api/v3/profile_metadata/available_years_serializer.rb
https://www.pivotaltracker.com/story/show/168375254
The problem was that the list of available years was taken from the wrong "readonly node"
=> Take list of years from the context-specific readonly node

frontend/scripts/react-components/tool/tool.component.jsx
The tooltip was missing on the layers info. As we use an ejs template in the map-dimensions component we cant use the react tooltip so we need to load the vanilla tooltip to the tool.
=> We need the vanilla tooltip as we use an ejs

app/models/api/v3/chart.rb, app/models/api/v3/readonly/dashboards/commodity.rb, app/models/api/v3/readonly/dashboards/company.rb, app/models/api/v3/readonly/dashboards/country.rb, app/models/api/v3/readonly/dashboards/destination.rb, app/models/api/v3/readonly/dashboards/source.rb, app/models/api/v3/readonly/dashboards_attribute.rb, app/models/api/v3/readonly/download_attribute.rb, app/models/api/v3/readonly/flow_node.rb, app/serializers/api/v3/dashboards/source_serializer.rb, app/services/api/v3/dashboards/filter_sources.rb, db/migrate/20190919063754_remove_parent_node_from_dashboards_sources_mv.rb, db/structure.sql, db/views/dashboards_sources_mv_v07.sql
https://www.pivotaltracker.com/story/show/168571749
This is to fix the bug with duplicated states in dashboards filters. The root cause of the bug is that Brazil states are returned twice, once with a parent (biome) as inferred from Brazil-soy supply chain, and once without a parent, as inferred from the Brazil-beef supply chain, which has no biomes. Clearly, this is not a good way to infer about parent nodes. I think these properties were not used anyway in the frontend (@sorodrigo ?), so I think it's better to remove and figure out a better way to do it without knowing which commodity we're looking at.
=> Removed parent name & node type from sources response

frontend/scripts/react-components/explore/explore.scss, frontend/scripts/react-components/explore/top-cards/top-cards.scss
Firefox screen:
Short chrome screen:
=> Fix screen overflowing in firefox and short screens

frontend/scripts/actions/app.actions.js, frontend/scripts/react-components/tool-links/tool-links.actions.js, frontend/scripts/react-components/tool/map/map.component.js, frontend/scripts/react-components/tool/map/map.container.js, frontend/scripts/react-components/tool/nodes-titles/nodes-titles.component.js, frontend/scripts/react-components/tool/sankey/node-menu.component.jsx, frontend/scripts/react-components/tool/sankey/node-menu.scss, frontend/scripts/react-components/tool/sankey/sankey-column.component.jsx, frontend/scripts/react-components/tool/sankey/sankey.component.jsx, frontend/scripts/react-components/tool/sankey/sankey.js, frontend/scripts/react-components/tool/sankey/sankey.scss, frontend/scripts/react-components/tool/sankey/sankey.selectors.js, frontend/scripts/react-components/tool/tool.component.jsx
This PR removed the node-titles vanilla component and replaces its functionality with a tooltip that appears on node hover plus a link to profiles that appears in the node menu.
=> Feat: sankey node tooltip + profiles node menu link

frontend/scripts/analytics/explore.events.js
The page was crashing because the param for linkParams had a wrong name
=> Fix analytics param

app/services/api/v3/nodes_stats/response_builder.rb, frontend/docs/swagger.yaml, spec/responses/api/v3/nodes_stats_spec.rb
Fix the error when `attribute_id` is not sent in `nodes_stats` endpoint. Now, the volume attribute is used by default if `attribute_id` is not specified.
=> Add default volume attribute for nodes_stats

frontend/scripts/react-components/tool/splitted-view/splitted-view.component.jsx
We weren't showing the arrows without the ENABLE_REDESIGN_PAGES flag
=> Show the Layout Arrows without the redesign flag

app/admin/api/v3/top_profile.rb
https://www.pivotaltracker.com/story/show/169118685
The restriction was in place possibly by design rather than a bug, but I agree it is not helpful to be very restrictive in this case.
=> Removed restriction for assigning top profile images

frontend/scripts/react-components/nav/filters-nav/filters-nav.selectors.js
This is a fix for a missing resize by dropdown in legacy
=> Restore resize by filter on legacy

config/deploy/demo.rb, config/deploy/indonesiademo.rb, config/deploy/sandbox.rb, config/deploy/staging.rb
This PR updates sandbox, demo, indonesiademo capistrano config to use nvm. I also updated staging, so all of them use `12` instead of `v12.12.0`.
I also installed node in those 3 envs. Production setup is a bit different, didnt feel like touching it.
I'm not sure if we also need to update the system node, because of rails dependency.
Let me know if this is good to go and I'll deploy to sandbox.
=> Feat: update sandbox demo indonesiademo node12

Gemfile, Gemfile.lock
Unfortunately there seems to be some incompatibility, probably between sidekiq and sidekiq-unique-jobs, so not upgrading to 6 for now
=> Downgraded sidekiq

app/serializers/api/public/attributes/flow_attribute_serializer.rb, app/services/api/public/attributes/response_builder.rb, db/migrate/20191111213756_add_unit_type_to_flow_attributes_mv.rb, db/structure.sql, db/views/flow_attributes_mv_v03.sql
Added the unit_type property to the attributes endpoint, so that users can understand better what kind of values they get. Also changed the name of the key from `attribute_id` to `id`, to keep it consistent with other endpoints.
=> Added unit_type to attributes response

config/deploy.rb, config/deploy/sandbox.rb
https://www.pivotaltracker.com/story/show/169724680
Adds deployment to a second sandbox instance. Only one of them is supposed to be running migrations, refreshing downloads and background jobs.
`cap sandbox deploy` will deploy to both servers
=> Added second sandbox instance

config/newrelic.yml
https://www.pivotaltracker.com/story/show/169861177
Trying to make NewRelic label hosts sensibly, so far the env var on its own didn't work.
When looking at sandbox overview in NewRelic, the hosts at the bottom of the page should have labels sandbox-data and sandbox-web
=> Added process host display name

config/deploy/sandbox.rb
https://www.pivotaltracker.com/story/show/169724680 (fix because IP changed...)
I didn't realise one of the hosts did not have a stable IP. Thus I stopped and started it and the IP changed. I have now associated that host with an elastic IP, which should prevent that from happening in the future.
`cap sandbox deploy` works for both hosts
=> Updated host address; also now associated with an elastic IP

app/controllers/api/public/nodes/destinations_controller.rb, app/controllers/api/public/nodes/exporters_controller.rb, app/controllers/api/public/nodes/importers_controller.rb, app/controllers/api/public/nodes/sources_controller.rb, app/controllers/concerns/api/public/nodes.rb
for some reason when in module doesn't work on staging
https://www.pivotaltracker.com/story/show/169912815
When skipping the context is included from a mixin, works on localhost but not on staging. 
This should work:
https://staging.trase.earth/api/public/nodes/exporters?commodity=SOY&country=BR
=> skip loading contexts directly in controller

frontend/scripts/react-components/nodes-panel/nodes-panel.fetch.saga.js, frontend/scripts/react-components/tool/tool.selectors.js
No link
We were using the shortcut in getSelectedColumnsIds to find the selectedColumnIds but some default columns were not added to the array resulting in null values.
I understand this early return helps performance but sometimes it causes some bugs we might want to remove it at some point
Go to Brazil - Soy and change last column (sandbox data)
=> We weren't adding default columns to flows fetch

frontend/scripts/react-components/tool/tool.actions.js
No links
We were having an error if there were no cartolayers. This layers should be added anyway for Brazil water scarcity:
Brazil Pork sankey (There is no edit layers)
=> Fix crash when missing carto layers

frontend/scripts/react-components/profiles/table/table.component.jsx
No links
Add units to all the rows of the table, not only the first
http://localhost:8081/profile-actor?nodeId=23089&contextId=1
Check DEFORESTATION RISK table
=> Units should be shown in all rows

app/services/api/v3/dashboards/base_filter.rb
https://www.pivotaltracker.com/story/show/169866403
Endpoint was not filtering destinations by year. With the changes in underlying materialised views we introduced recently that is now possible.
Use urls from the PT, or go through dashboards selecting Brazil soy from Sorriso, Germany should not be coming up in destinations panel.
=> Fix: Germany not Sorriso destination in 2017

frontend/scripts/react-components/nodes-panel/destinations-panel/destinations-panel.component.jsx, frontend/scripts/react-components/nodes-panel/destinations-panel/destinations-panel.js, frontend/scripts/react-components/nodes-panel/nodes-panel.modules.js, frontend/scripts/utils/pluralize.js
https://www.pivotaltracker.com/story/show/170123242
Add tabs to destination panel
Go to dashboards and destination panel. You should see two tabs in sandbox data
Note: There might be some changes in the Sankey. Mostly about the column switch
=> Add tabs to destination panel

app/services/api/v3/import/importer.rb
https://www.pivotaltracker.com/story/show/170278697
materialized view with aggregated values was not refreshed; now refreshed as part of the import process
=> Refresh nodes_stats_mv during import

app/admin/api/v3/context_node_type_property.rb, app/models/api/v3/context_node_type.rb, app/models/api/v3/context_node_type_property.rb, app/serializers/api/v3/node_types/node_type_serializer.rb, app/services/api/v3/node_types/filter.rb, db/migrate/20191212151744_add_geometry_node_type_id_to_context_node_type_properties.rb, db/schema_comments.yml, db/structure.sql, frontend/scripts/react-components/profile-node/profile-node.reducer.js, frontend/scripts/react-components/tool-links/tool-links.reducer.js, frontend/scripts/react-components/tool/map/map.component.js, frontend/scripts/react-components/tool/tool.actions.js, spec/models/api/v3/context_node_type_property_spec.rb, spec/support/contexts/api/v3/brazil/brazil_context_node_types.rb, spec/support/schemas/v3_columns.json
https://www.pivotaltracker.com/story/show/170277633
Added a new column in context_node_type_properties, which allows to link to a different context node type in same context.
columns endpoint:
=> Adds a way to configure shared geometries

config/deploy/production.rb
https://www.pivotaltracker.com/story/show/170357672
There is now a load balancer in front of two production machines, like in sandbox.
`cap production deploy` deploys to two instances, runs migrations & generates sitemap only on one (the `data` one, which is a better machine)
=> Added second production instance

app/services/api/v3/flows/filter.rb, app/services/api/v3/flows/result.rb, spec/services/api/v3/flows/filter_spec.rb
https://www.pivotaltracker.com/story/show/169391952
A change in how values are calculated for the "OTHER" nodes.
Before:
- find top nodes for each column
- fetch all flows (~ 1 million for Brazil beef)
- for each flow, for each element of the path, if it's one of top nodes then leave it alone, if it's not replace with 'OTHER'
- group nodes by path
- end up with ~ 1400 flows
Now:
- find top nodes for each column
- fetch flows with non-top node ids already substituted with 'OTHER' and grouped by path (~ 1400 flows)
- done
Compare the outputs. That's easiest done when comparing visually using the sankey, if you have the same database as one of the dev environments. Ideally the same as sandbox, so that you can observe the difference in performance for Brazil beef.
=> Group flows through "OTHER" in the database rather than in ruby

Gemfile, Gemfile.lock
https://github.com/Vizzuality/trase/pull/656
https://github.com/Vizzuality/trase/pull/1032
https://github.com/Vizzuality/trase/pull/1102
[A while back we added 3 gems to the Gemfile](https://github.com/Vizzuality/trase/pull/656): `rbnacl`, `rbnacl-libsodium` and `bcrypt_pbkdf`. That helped solve an issue while deploying with Capistrano. The issue was caused by the fact that in order to use some kinds of keys those dependencies were required by net-ssh.
One of those gems, `rbnacl-libsodium`, is now discontinued, so it makes sense to revisit.
I think the root cause might have been to enable support for ed25519 keys, and if that is the case we should use the solution described in [net-ssh readme](https://github.com/net-ssh/net-ssh) and in [this …
=> ed25519 support

app/admin/api/v3/chart_node_type.rb, app/models/api/v3/chart.rb, app/models/api/v3/context.rb, app/models/api/v3/profile.rb, app/services/api/v3/actors/basic_attributes.rb, app/services/api/v3/actors/exporting_companies_plot.rb, app/services/api/v3/actors/sustainability_table.rb, app/services/api/v3/actors/top_countries.rb, app/services/api/v3/actors/top_nodes_summary.rb, app/services/api/v3/actors/top_sources.rb, app/services/api/v3/places/basic_attributes.rb, app/services/api/v3/places/indicators_table.rb, app/services/api/v3/places/mini_sankey.rb, app/services/api/v3/places/top_consumer_actors.rb, app/services/api/v3/places/top_consumer_countries.rb, app/services/api/v3/places/trajectory_deforestation_plot.rb, spec/controllers/api/v3/actors_controller_spec.rb, spec/controllers/api/v3/places_controller_spec.rb, spec/responses/api/v3/exporter_profile_spec.rb, spec/responses/api/v3/importer_profile_spec.rb, spec/responses/api/v3/place_profile_spec.rb
https://www.pivotaltracker.com/story/show/170710420
(and a number of other bugs of similar type, concerning profile pages)
All profile pages endpoints have checks for required configuration, which result in error 500 thrown when configuration is missing. It should be a 404 error, which combined with the descriptive message should help with debugging and reduce the error rate.
e.g.
https://sandbox.trase.earth/api/v3/contexts/6/actors/36641/top_sources
=> Raise 404 instead of 500 when profile configuration incomplete

doc/gh-pages/api/trase_public_api_1.1.html, doc/gh-pages/api/trase_public_api_1.1.oas3.yaml
https://www.pivotaltracker.com/story/show/170797616
Describes an additional endpoint, `nodes/data`, that I think in combination with `top_nodes` (another new endpoint which should cover GFW) should cover the needs of Trase finance. Will share the spec with them to discuss and iterate, but would like it available on gh pages for reference so
When merged to develop, should be available at https://vizzuality.github.io/trase/api/trase_public_api_1.1.html
=> Proposed endpoints for Trase finance

app/services/api/v3/dashboards/charts/multi_year_ncont_overview.rb, app/services/api/v3/dashboards/charts/single_year_ncont_node_type_view.rb, app/services/concerns/api/v3/dashboards/charts/flow_values_helpers.rb, spec/services/api/v3/dashboards/charts/multi_year_ncont_overview_spec.rb, spec/services/api/v3/dashboards/charts/single_year_ncont_node_type_view_spec.rb, spec/support/schemas/dashboards_charts_multi_year_ncont_overview.json, spec/support/schemas/dashboards_charts_single_year_ncont_node_type_view.json
https://www.pivotaltracker.com/n/projects/2380431/stories/171324947
Bug present in "multi year overview" and "single year node type view" when ncont attribute "biome" selected - the legend would include biomes from both Brazil and Paraguay.
Fixed by retrieving values from data.
Before
After
=> Fixed ncont values legend

app/services/api/v3/dashboards/filter_meta.rb
by picking one from distinct profile type & prefix combinations
https://www.pivotaltracker.com/story/show/170319809
Initially I thought we could just remove profile type from that response to remove the duplicates, but sadly that breaks profile pages "browse" function. And wouldn't solve the problem anyway, because sometimes the difference would be in the prefix not the profile type:
Changed the query instead, so that it groups by node type id / name only and picks `MAX` of whatever it finds in profile and prefix columns. In case of strings, `MAX` will pick whatever is "biggest" in lexicographic order, including a not-null value over a null value. Not perfect. Ideally we wouldn't need the profile name / prefix value before the commodity is selected, because it's impossible to render a …
=> Remove duplicated node types

.rubocop_todo.yml, app/services/api/v3/actors/exporting_companies_plot.rb, lib/api/v3/profiles/flow_stats_for_node_type.rb
https://www.pivotaltracker.com/story/show/170797923
Use partitioned_flow_values in exporting_companies plot. Also fetch data one attribute at a time. Previously we have 2 queries - first one to fetch the production values (axis y) and a second one to fetch x values for a number of attributes. Now each attribute on x is fetched separately, which makes the query simpler (grouping) and so the 3 queries are faster than 2 queries were. The ruby logic was amended to match, also simplifying how data from those combined queries is pulled into the result.
Test difference with Brazil beef, e.g. `/api/v3/contexts/6/actors/23723/exporting_companies?year=2017`
=> OPTIMISE ACTOR -> EXPORTING COMPANIES ENDPOINT

app/services/api/v3/dashboards/parametrised_charts/node_types_to_break_by.rb
https://www.pivotaltracker.com/story/show/171514946
Country of import first, then exporter, then importer (where available) followed by all the rest in the order they appear in the supply chain.
=> Sort "node type charts" with sticky node types first

app/services/api/v3/flows/filter.rb, app/services/api/v3/flows/result.rb
https://www.pivotaltracker.com/story/show/171932938
Adds to flows endpoint information about number of nodes aggregated as "OTHER"
`include`->`otherNodes`
It is an array (corresponding to column positions), e.g.:
"otherNodes":[{"id":38980,"count":2152},{"id":38983,"count":305},{"id":38984,"count":209},{"id":38985,"count":63}]}}
=> Return number of aggregated OTHER nodes

frontend/scripts/react-components/tool-links/tool-links.initial-state.js, frontend/scripts/react-components/tool-links/tool-links.reducer.js, frontend/scripts/react-components/tool/sankey/sankey-column.component.jsx, frontend/scripts/react-components/tool/sankey/sankey.component.jsx, frontend/scripts/react-components/tool/sankey/sankey.js, frontend/scripts/react-components/tool/sankey/sankey.scss
https://www.pivotaltracker.com/story/show/171812712
- Added the tooltip for 'Other' node with the count and the unit indicator information
- Removed the click interaction and changed the cursor to default
Go to the tool in Sankey view and hover over an 'Other' node
=> Remove interaction and add others node count

frontend/scripts/react-components/profile/profile-components/summary/country-summary.component.jsx
https://www.pivotaltracker.com/story/show/172048393
We have the country name coming from the profile meta now. And the country is rendered in red.
=> Add country name from profile meta

app/services/api/v3/import/restore_yellow_table.rb
No link, bug identified when testing something else.
The issue affects restoring "yellow tables", that is tables managed via the CMS, which link to "blue tables", that are updated during the data update process. One step involves checking if any yellow table records became obsolete because of one or more of the blue table records they depend on got removed; the condition for checking that was incorrect.
In my case the process failed when restoring "quant_context_properties" - I had some defined where the quant involved got removed.
=> If any of the blue keys is null (= blue record removed), delete yellow record

config/deploy.rb
N/A
Capistrano was upgraded but lock was not updated accordingly
`cap ... deploy` works now
=> Updated Capistrano lock

frontend/scripts/react-components/nav/top-nav/top-nav.scss, frontend/scripts/router/nav-links.js
A new Trase finance link has been added to the navbar linking to trase.finance
The nav breakpoint to change to the hamburger button has been changed to 1060px.
Should we review the mobile view and add the logo?
This link is included in the navbar so it should work in the different pages of Trase
=> Add Trase Finance Link

db/migrate/20200522153602_remove_trader_and_empty_geo_id_from_map_attributes_values.rb, db/structure.sql, db/views/map_attributes_values_v_v02.sql
https://www.pivotaltracker.com/story/show/172973211
Removes nodes with empty geo_id from the export, as well as nodes with new "trader" type geo_id
=> Removed empty geo_ids and trader geo_ids from map attributes export

app/models/api/v3/chart.rb
https://www.pivotaltracker.com/story/show/173149769
Chart type comes empty and chart is not drawn, regression from refactoring code in preparation for country profiles
Any trader profile, e.g. Cargill Paraguay soy
=> Fix for missing chart type due to misspelt identifier

app/services/api/v3/top_profiles/derive_top_profile_details.rb
https://www.pivotaltracker.com/story/show/173605166
Issue with retrieving readonly node, which needs to be looked up by node_id + context_id rather than just node_id
=> Fixed deriving top profile summary

frontend/scripts/react-components/nodes-panel/nodes-panel.saga.js, frontend/scripts/react-components/tool-links/tool-links.reducer.js
It seems that changing a context was breaking the map.
We were deleting the columns to be able to select the column of the node selected on the panel and this was breaking the context change.
We can reset everything on context change on the NODES_PANEL reducer on tool links. The problem was that the context change or not was not properly known on nodes-panel.saga
Now the context can be changed and the change of column still works
Go to the tool and select a different context on the panel (country + commodity) and save - It shouldn't break
Also, select a node from a different column on source - It should be selected when we save
Remember that some of the nodes don't work right now. E.g Abaete doesn't work but Abadia de Goias does
=> Fix context change crash

frontend/scripts/react-components/profile/profile-components/summary/actor-summary.component.jsx
None
Profile actors where missing the new "sticky" header, this pr adds the same logic as on the other profiles where the header sticks when scrolling.
go to for example http://localhost:8081/profile-actor?nodeId=23670&contextId=1 and make sure the header sticks!
=> Add react sticky-node on profile actors

frontend/scripts/react-components/shared/profile-selector/profile-selector.component.jsx, frontend/scripts/react-components/shared/profile-selector/profile-selector.scss
This fixes the scroll on the profiles panel. Before, the save button wasn't clickable sometimes. Now we have a scroll like in the tool panel.
=> Fix profile panel scroll

app/services/api/v3/country_profiles/basic_attributes.rb
This value will come from FAO and will be supplied through node quants, at present nothing to show there.
https://basecamp.com/1756858/projects/12498794/todos/410599687#comment_759372992
=> Removed agricultural exports / imports value (incorrectly calculated)

frontend/scripts/react-components/shared/tags-group/tag.component.jsx
https://www.pivotaltracker.com/story/show/174356544
Dynamic sentence (tag component at the end) was applying lowercase except for some explicit transforms. We shouldn't do this. In this case, "Mt" was being transformed into "mt".
http://localhost:8081/flows/data-view?toolLayout=1&countries=107&commodities=6&selectedColumnsIds=0_24-1_6-2_7-3_8
=> Parts should retain case

frontend/scripts/react-components/dashboard-element/dashboard-widget/dynamic-sentence-widget/dynamic-sentence-widget.selectors.js, frontend/scripts/react-components/dashboard-element/dashboard-widget/node-indicator-sentence-widget/node-indicator-sentence-widget.selectors.js, frontend/scripts/react-components/dashboard-element/dashboard-widget/ranking-widget/ranking-widget.component.jsx, frontend/scripts/utils/formatDynamicSentenceValue.js
The problem was not solved with the last PR as there were actualli some milli tons apart from the capitalisation. Now they are displayed as "< 1 t" for tons unit
http://localhost:8081/flows/data-view?selectedContextId=43&toolLayout=1&countries=50&commodities=87&exporters=13566&selectedColumnsIds=0_13-1_6-2_7-3_8
=> Return < 1 for less than 1 ton

app/models/api/v3/context_node_type_property.rb, app/services/api/v3/import/restore_yellow_table.rb
Previously context node type ids could be restored incorrectly because the nullable geometry id was not handled properly
Also, schema renamed from tool_tables to trase_earth
=> Database update fixes

frontend/scripts/react-components/profile/profile-components/line/line.component.jsx, frontend/scripts/react-components/profile/profile-widgets/deforestation-widget.component.jsx, frontend/scripts/react-components/profile/profile-widgets/line-widget.component.jsx
none 
This pr adds support for multiple axises, new property added to api multi_unit will determine if type=line should be represented as a secondary yaxis to the right. This is currently effecting the DEFORESTATION TRAJECTORY widget.
got to: http://localhost:8081/profile-country?nodeId=26&contextId=58 and make sure y2Axis appears
go to any other dashboard using the line chart and make sure any previous behaviour is still the same when `multi_unit` is set to false.
=> add multi axis support for line chart

.env.sample, .travis.yml, lib/tasks/db_remote_import.rake
Renames `tool_tables` to `trase_earth` to reflect the recent name change on Trase's systems.
@agnessa I presume we will need to update the environment variables on the various servers too? All future dumps we make will be using `trase_earth`, so we are good to do this 👍
=> Schema rename

app/services/api/v3/countries_com_trade_indicators/world_request.rb, app/services/api/v3/countries_wb_indicators/api_service.rb, app/services/api/v3/countries_wb_indicators/wb_request.rb
https://appsignal.com/vizzuality/sites/5a7350b4b504f531d85ecf75/exceptions/incidents/420?timestamp=2020-09-08T00%3A00%3A11Z
Context: the fix applies to a process that synchronises data in the Trase DB with 2 external APIs, the World Bank API and the Com Trade API. The processing happens in sidekiq jobs, and sometimes we get connectivity errors that result in data not being fully synchronised.
WB importer: was not handling http error codes from the API correctly, i.e. it was returning an empty array which ended up as a conversion error in the parsing logic that follows. Instead of that, we're now raising an exception, which has the additional effect of making sidekiq schedule a retry (sometimes there are connection issues with the WB AP). Removed the logic that reported the error to …
=> Handle error response from WB API

frontend/scripts/react-components/explore/explore.component.jsx
https://www.pivotaltracker.com/n/projects/2380432/stories/175073497
This pr fixes crash happening on step 3 explore when levels are not available. 
Api URL needs to point to sandbox to reproduce, make sure step 3 does not crash.
=> fix crash when levels are not available on explore step 3

frontend/styles/_settings.scss
https://www.pivotaltracker.com/story/show/175070916
WIP: Waiting for pallette approval and knowing if we need to add colors for Coffee too.
Go to Brazil cocoa and select 'Product' indicator
=> Add cocoa product thematic colors

config/deploy.rb
node_modules has grown in size and old releases take up a lot of disk space; before upscaling the storage, just reduce the number of releases to keep
=> Only keep 3 releases

frontend/scripts/react-components/tool/mapbox-map/mapbox-map.component.jsx
Reset tooltip items when we change of context
Before:
- Go to Brazil-Soy: Select a unit layer with the edit layers modal
- Hover over a region: You should see one or two tooltip items
- Go to Ecuador-Shrimp
- Hover over a region: The same items were remaining
Now:
- ...
- Tooltip items are reset
=> Reset tooltip

frontend/scripts/react-components/explore/explore.component.jsx, frontend/scripts/react-components/explore/explore.selectors.js, frontend/scripts/react-components/shared/grid-list-item/grid-list-item.component.jsx, frontend/scripts/react-components/shared/grid-list-item/grid-list-item.scss, frontend/scripts/react-components/shared/help-tooltip/help-tooltip.component.jsx, frontend/scripts/react-components/shared/help-tooltip/help-tooltip.scss, frontend/scripts/react-components/tool-links/tool-links.selectors.js, frontend/scripts/react-components/tool/timeline/timeline.component.jsx, frontend/scripts/react-components/tool/timeline/timeline.scss, frontend/styles/_tooltip.scss
Please include the link(s)
This pr adds highlight difference between nat/subnat when choosing a commodity and years within sankey timeline. 
1. Go to /explore and make sure highlighting works as expected
2. Enter sankey, make sure years that does not have subnat data display a tooltip letting the user know that data is only national. 
3. On sankey, make sure sub nat years are highlighted and does not display a tooltip. 
@agnessa would be awesome if we could verify the data works correctly, I'm now using `subnationalYears` instead of `isSubnational` as we discussed from the context API, so after this PR is merged we can safely remove that key from the endpoint.
=> add nat subnat highlight

frontend/scripts/react-components/shared/profile-selector/profile-panel/profile-panel.component.jsx
This was a strange bug. We had some of these caused by transifex translations before
Adding some keys to the main Headings has fixed it. Anyway, we should be aware of these bugs and maybe find a more general solution at some point.
- Enter profiles page with a language other than 'en'
- Select and go through the panel steps 
- The mounting and unmounting of the same Heading on some step was crashing, not anymore
=> Headings needed a key to fix crash

frontend/scripts/app/app.component.jsx, frontend/scripts/tests/iframe/index.html, frontend/scripts/utils/isIframe.js
Iframes containing the app shouldn't show the cookie banner
Run a server like [SimpleHTTPServer](https://www.pythonforbeginners.com/modules-in-python/how-to-use-simplehttpserver) in the tests/iframe folder. That should open the app inside an iframe. The banner shouldn't show
=> Don't show cookie banner on iframe

frontend/styles/_settings.scss
New colors added for Zero deforestation commitment indicator on Cote d'ivoire - Cocoa and Indonesia - Wood Pulp
yes - green
no - red
Unknown remains gray
Go to those contexts and select ZDC indicator
=> Add thematic colors for zero deforestation commitment

app/services/api/v3/places/basic_attributes.rb
I couldn't test this as I didn't have the data for this specific context. Please feel free to make any modifications
https://app.asana.com/0/1187619191620560/1199231338050928/f
The total commodity and unit should only appear if we have it. Maybe we have to apply this too to the actors' basic_attributes.
Search for 'Pt Arari abadi' on the profiles page. The text should be correct, without the "occupying a total of land" part
=> Add total of commodity area only if we have it

frontend/package.json, frontend/scripts/utils/pluralize.js, frontend/yarn.lock
https://app.asana.com/0/1187619191620560/1199244035527549/f
This PR improves the pluralize function using the pluralize package and pluralizing by default the last word of a string. The exceptions are less now.
Go to the data section of Ecuador - Shrimp. You should see all correct plurals, including 'parishes' and 'exporter groups'
=> Improve pluralize

frontend/scripts/react-components/profile/profile-components/scatterplot/scatterplot.component.jsx
https://app.asana.com/0/1187619191620560/1199241958938734/f
Very small change just adjusting the margin of the scatterplot left axis labels
Try with different profiles
=> Change margin to fit tick label

frontend/scripts/constants.js, frontend/scripts/react-components/tool/sankey/sankey.component.jsx
https://app.asana.com/0/1187619191620560/1199241958938727/f
The country of production node is always "selected" but not actually. As we just have one node and its the full country its not selectable but we still want to see the link to the country profile.
Solution: On hover of the country profile node you will always see the 'Go to country profile' link. If some other node is selected you will be able to expand, clear, ...
Remember to have ENABLE_COUNTRY_PROFILES set to true on the env. Go to any context with a country of production column and select it. You should be able to see and use the link on hover
=> Allow country menu profile link

frontend/scripts/constants.js
Volume on the sankey tooltip was defaulting to one decimal. Now 0 decimals are specified
=> Update 'volume' indicator number of decimals

frontend/scripts/react-components/profile/profile-widgets/map-flows-widget.component.jsx
https://app.asana.com/0/1195054825337974/1197993057162668/f
This is part of the task, not the main purpose (that was solved before). The top destinations map widget was not showing as we were missing a param (context or commodity id depending if its an importer or exporter country)
Check exporting or importing countries profiles
=> Add missing prop

frontend/scripts/react-components/tool/sankey/sankey.component.jsx
https://app.asana.com/0/1187619191620560/1199241958938727/f
The country of production node hover menu was not showing on staging. It had a condition to have ENABLE_COUNTRY_PROFILES turned on but actually if we have something selected it should open have a menu.
Now it should open on staging to have the general options and if we have the tag selected it should show the link to the profile too
Go to the Sankey and change the first column into 'Country of production'
If you don't have ENABLE_COUNTRY_PROFILES selected the hover over the first node won't show immediately but it should show after you click in another node
=> Update condition to show country hover menu

frontend/scripts/react-components/dashboard-element/dashboard-widget/ranking-widget/ranking-widget.component.jsx
This pr fixes an issue for importer/exporter group widgets, not uppercasing CO labels.
=> add exporter/importer groups in uppercase condition

frontend/scripts/react-components/chart/tick/category-tick.component.jsx
We dont want to show this links to country profiles if they are not active
=> Don't show the link on Data if the flag is off

frontend/scripts/react-components/home/home-video/home-video.component.jsx
NoCookie didnt have the right route on config its under the youtube object of Plyr. This was making the video fail
=> Fix config route of noCookie

frontend/scripts/react-components/profile/profile-components/scatterplot/scatterplot.scss
https://app.asana.com/0/1195054825337974/1199241958938734/f
Label should be aligned to the right to avoid being cut
- Go to Minerva profile
- Go to last chart
- Select last tab
- x axis label should read correctly
=> Align label to the right

app/services/api/v3/places/basic_attributes.rb
https://app.asana.com/0/inbox/1191186791596033
These can be companies (notably for Indonesia Wood Pulp) where the capitalisation is a trademark. To get around this we always present these company names in UPPERCASE to make it clear that we are not implying any specific capitalisation.
This PR relates to the following screenshot of a indonesia pulp wood wood supplier profile:
Check the wood supplier profiles for indonesia wood pulp and ensure that the company names are always in capitals.
=> Capitalise region names on the place profiles

config/appsignal.yml
Leave exception reporting in sandbox and production to reduce noise.
=> Disable AppSignal in staging, demo and indonesiademo

app/models/content/user.rb
Creating users in the CMS was affected by db changes related to token authentication. We need to populate provider / uid fields, otherwise validations prevent the user from saving.
=> Fixes failing validation when creating users (regression from token authentication)

frontend/scripts/react-components/tool/sankey/sankey.component.jsx
https://app.asana.com/0/1187619191620560/1199241958941726/f
The fix on the tooltip was intended for importing countries (countries that receive commodities) not Importer
=> The updated country has to be on the importing country not importer

frontend/scripts/react-components/tool/sankey/sankey.component.jsx
https://app.asana.com/0/1198886845396491/1199904387610021/f
Scrolling was not working well with tooltips on the nodes of the sankey. When you select all nodes and you scrolled the tooltip was misplaced or gone.
- Go to any context with many nodes ex. Brazil-Soy
- Change 'Change view' to "All nodes"
- Scroll down
- Hover over a node - The tooltip should appear correctly
=> Add scroll offset to y tooltip reference

frontend/scripts/analytics/data-portal.events.js
https://app.asana.com/0/1187619191620560/1199979503038581/f
The analytics event on the logistics download was causing an error as we dont have contexts for this
Go to downloads page. Select logistics bulk download and try to download one.
=> Optional contexts on analytics event

frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget-label.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.component.jsx, frontend/scripts/react-components/dashboard-element/dashboard-widget/dashboard-widget.scss
https://app.asana.com/0/1198886845396491/1199896185325402/f
Add suffix as the unit to the charts. We only need it on the default charts as the others have the unit implemented. Is important not to use caps as 't' is a different unit than 'T'
Go to the data view of any context. You should be able to see the units on the lower right of the default charts. Change some indicator and units just to test
=> Add unit to default chart on widgets

frontend/scripts/react-components/nav/top-nav-redesign/tabs/tools-insights.component.jsx, frontend/scripts/router/nav-links.js
The top nav bar is linking to https://insights.trase.earth/insights. I'm not sure if this was intentional, but these days it should be https://insights.trase.earth
=> Fix URL for insights page

app/workers/node_with_flows_refresh_actor_basic_attributes_worker.rb
https://appsignal.com/vizzuality/sites/5ac78a01fc940e7ec5927d5b/exceptions/incidents/320
When context goes missing after the worker had been scheduled, it fails with an exception way down in the basic attributes service. Instead it should bail out immediately, silently.
=> Terminate refresh worker immediately if context is no longer available

frontend/styles/_settings.scss
https://app.asana.com/0/1199888630756445/1200121713476651/f
Set up colors for the new indicator product. Which will have different values for each commodity. Right now we added the colors for soy and meat. This should work for example in Argentina - Soy as well as Paraguay - Soy
Go to the Sankey in Paraguay - Beef for example. Choose product on the change indicator button. You should see the new colors
=> Add indicator colors for soy and beef products

frontend/scripts/react-components/shared/world-map/world-map.selectors.js
https://app.asana.com/0/0/1200168441943756/f
The greatCircle function from turf was unable to compute a value with the same source and destination. We are not showing this arc on the map as it won't be visible anyways. Maybe we can find another design solution
Go to Paraguay Beef exporter profile and check the exports map
http://localhost:8081/profile-country?nodeId=396&contextId=7
=> Dont show breaking arc

.env.sample, app/services/api/v3/map_attributes_carto_sync.rb, app/services/api/v3/map_attributes_export.rb, spec/services/api/v3/map_attributes_export_spec.rb
Apparently file name matters for Carto sync; include the environment name in the exported file name so that it matches the expected table name.
=> Include env name in map attributes export for Carto sync

frontend/scripts/react-components/tool/map/map.component.jsx, frontend/scripts/react-components/tool/map/map.hooks.js
https://app.asana.com/0/1199888630756445/1200090386437943/f
This solution could be improved
The problem is that the unit layer (Eg. paraguay_department) was not loaded on time sometimes to show the choropleth. So the map was showing without the colored choropleth but with a legend.
I added a loading layers state to fix this.
Probably this check is running too many times and can be improved
Also, we have to check if this is the only cause of the missing choropleth
Go to a context (Paraguay soy) you should see the choropleth at first no matter how many times you reload (It was showing intermittently before)
=> Add loading state to be sure that unit layer is loaded

frontend/scripts/react-components/shared/tags-group/tags-group.component.jsx
https://app.asana.com/0/0/1200265497316742/f
Very small change. The prefixes were not being sent to transifex as they had a notranslate class. This is still added on the Tag component so its fine removing it from the tag group
You can see that the profixes like "for" and "in" in the data view dont have a notranslate class anymore
=> Remove no-translate.It is aready added on Tag

Gemfile, Gemfile.lock
(undefined method `[]' for nil:NilClass)
=> Downgraded capistrano-passenger back to 0.2.0

app/services/api/v3/country_profiles/basic_attributes.rb, config/initializers/boolean_false_values.rb
https://app.asana.com/0/0/1200168441943759/f
Instead of checking for presence of the signatory quals, we need to parse the YES / NO values.
Argentina should not be a signatory of either nydf or adp. Belgium should be a signatory to nydf, but not adp. France should be a signatory to both.
=> We need to parse 'YES' and 'NO' values for signatory quals

app/services/api/v3/actors/basic_attributes.rb, app/services/api/v3/country_profiles/basic_attributes.rb, app/services/api/v3/country_profiles/external_attribute_value.rb, app/services/api/v3/node_attribute_values_preloader.rb, app/services/api/v3/places/basic_attributes.rb, app/services/api/v3/places/indicators_table.rb, app/services/api/v3/profiles/indicators_table.rb
To make it clear that some WB indicator values might be from previous years, we add the year to the tooltip. The approach could be applied to other indicators, where data does not cover the range of years on a country profile, but for now we only have the fallback behaviour active for WB indicators.
Go to https://sandbox.trase.earth/profile-country?nodeId=541&year=2016&contextId=1
Observe, that the value of GDP sometimes does not change when you select different years, that is because the latest year of data is from 2014. So if you're on a more recent year, you should see '(2014)' appended to the tooltip.
=> Added ability to lookup both value and year, to enrich tooltips

app/services/api/v3/node_attributes/filter.rb
https://app.asana.com/0/1199888630756445/1200151592420074/f
Fixed issue in query, which should filter by a single map attribute id only.
=> Map attributes query should take one map attribute id only

app/services/api/v3/profiles/stacked_line_chart.rb
Caused by changes to fetching preloaded attributes value + year
=> Fixed regression in place trajectory deforestation chart

app/services/api/v3/country_profiles/commodity_totals.rb
Caused by changes to fetching preloaded attributes value + year
=> Fixed regression in commodity totals chart

app/services/api/v3/country_profiles/commodity_totals.rb
Caused by changes to fetching preloaded attributes value + year
=> Fixed regression in commodity totals chart (cnt)

app/controllers/api/v3/country_profiles_controller.rb, app/controllers/concerns/api/v3/profiles/cross_context_helpers.rb, app/services/api/v3/country_profiles/top_source_countries_chart.rb
Affected by bad parametrisation and lack of results from com trade.
https://app.asana.com/0/0/1200168442660964/f
Firstly, this chart should be parametrised with commodity id instead of context id, but often it is parametrised incorrectly and in the long run better to protect it from the inside. We need to make sure it always runs a cross-context search.
Secondly, oddly in case of USA there seem to be no results from ComTrade. In such case we should be showing results from Trase only.
Go to USA importer profiles and there should be flows on the sourcing countries chart.
=> Fixed source countries chart

app/services/api/v3/country_profiles/top_source_countries_chart.rb
https://app.asana.com/0/0/1200168442660956/f
Possibly makes no sense to have values in kg and tonnes in same chart.
=> Convert netweight in kg to make sense with tonnes in the same chart

frontend/scripts/react-components/new-home/entrypoints/entrypoints.component.jsx, frontend/scripts/react-components/new-home/home.component.jsx, frontend/scripts/react-components/new-home/home.container.js
https://app.asana.com/0/1199888630756445/1200396125571535/f
The link from the homepage to the tool didn't contain the context and was making it impossible to change it.
Maybe we could later check how the tool could work without context.
Go from the home links to the tool and change the context
=> Add default context to link params

app/controllers/api/private/configuration_export_events_controller.rb, app/workers/configuration_export_worker.rb, frontend/docs/backend/cms_configuration_automation.mdx
There's a problem with jobs getting stuck in QUEUED, might be caused by all the logic we have in place to avoid multiple exports running simultaneously. Simplified by removing that, since it is a read-only operation anyway.
=> Simplification for the configuration export endpoint

frontend/scripts/react-components/tool/map/map.selectors.js
https://app.asana.com/0/1187619191620560/1200417420098935/f
Remove unit indicators information from tooltip layers
before:
after:
Hover over the sankey node and the region on the map. Only the sankey node should have that extra information
=> Remove map tooltip indicators information

app/services/api/v3/node_attributes/filter.rb
https://app.asana.com/0/1201203990997962/1201196267978619/f
See if it helps to suppress nodes from non-geo columns in the node attributes endpoint
https://sandbox.trase.earth/flows?toolLayout=1&countries=107&commodities=87&selectedColumnsIds=0_9-1_24-2_20-3_19
edit map layers, change something there
observe tooltip on Sinar Mas exporter group - it should NOT include any other attribute than volume
=> Exclude attribute values for nodes from non-geo columns

app/controllers/api/v3/destination_stats_controller.rb, app/services/api/v3/destination_stats/response_builder.rb, config/routes.rb, spec/services/api/v3/destination_stats/response_builder_spec.rb
[Please include the link(s)](https://app.asana.com/0/1201503005195814/1201415552712087/f)
The idea is to use the [new endpoint destination_stats](https://sandbox.trase.earth/api/v3/destination_stats?contexts_ids=1%2C2%2C4%2C38&attribute_id=1153) 
as replacement for the [old endpoint nodes_stats](https://sandbox.trase.earth/api/v3/nodes_stats?contexts_ids=1%2C2%2C4%2C38&attribute_id=1153&column_id=18)
The new endpoint doesn't allow parametrisation by column_id, because it handles all types of destination node types depending on context. It also doesn't accept other_attributes parameter like the old endpoint (I didn't think it was used on the explore page, and used the opportunity to simplify)
To replace, just change the name of the endpoint and use the current params except the column_id.
=> New endpoint to handle flows on the explore page without cumbersome parametrisation

app/services/api/v3/country_profiles/import_trajectory.rb
https://appsignal.com/vizzuality/sites/5a8317dfe2954e5d54c8cf8c/exceptions/incidents/330?timestamp=2022-02-16T02%3A24%3A54Z
undefined method `dig' for nil:NilClass
app/services/api/v3/country_profiles/import_trajectory.rb:65
=> Preventing nil exception when data missing

frontend/scripts/react-components/explore/explore.selectors.js
https://app.asana.com/0/1201203990997962/1201243968311708/f
We were previously checking for the subnationalYears attribute to decide on the grid item border color. Now we check for the isSubnational value
Go to explore page, select wood pulp, Argentina should have a black border
=> Use isSubnational instead of subnationalYears

app/models/api/v3/ind_property.rb, app/models/api/v3/quant_property.rb, db/migrate/20220318110509_refreshing_attributes_after_rounding_configuration_change.rb, db/structure.sql
https://app.asana.com/0/1201503005195814/1200420401286318/f
Sometimes as a result of an update of ind / quant attributes (e.g. changing the rounding setting), the attributes table is refreshed incorrectly in such a way that the ind / quant disappears from it completely. I believe this was due to a small omission in the upsert function, which is responsible for refreshing.
- go to https://indonesiademo.trase.earth/content/admin/ind_properties/
- edit a property, change power of 10 rounding of a selected attribute
- go to https://indonesiademo.trase.earth/api/v3/attributes, check the attribute is there with refreshed rounding setting
=> Fixed refreshing attributes after rounding configuration change

app/services/api/v3/flows/filter.rb
https://app.asana.com/0/0/1202210274720971/f
The ordering of UNKNOWN nodes was purposefully done so as to hide them from view - I disabled that logic
=> Disable ordering UNKNOWNs last

lib/tasks/benchmarks.rake
https://app.asana.com/0/1204397776707447/1204412736815622/f
Adds a simple rake task to simplify running benchmarks with different instance sizes.
[production|sandbox] bundle exec rake benchmarks:run
=> Benchmarks for Indonesia palm data endpoints

app/controllers/api/v3/newsletter_subscriptions_controller.rb, app/services/api/v3/create_newsletter_subscription.rb, spec/controllers/api/v3/newsletter_subscriptions_controller_spec.rb
https://app.asana.com/0/1204397776707447/1204397776707437/f
Mailchimp error message needed being parsed out.
When subscribing with the same email address the second time, instead of status 200 with payload:
```
{"error":"{:status=\u003e400, :response_body=\u003e\"{\\\"title\\\":\\\"Member Exists\\\",\\\"status\\\":400,\\\"detail\\\":\\\"agnieszka.figiel@vizzuality.com is already a list member. Use PUT to insert or update list members.\\\",\\\"instance\\\":\\\"d11f4c84-4c79-3f4f-8583-0ba5abddc6d4\\\"}\"}"}
```
we now get a status 400 with payload:
```
{"error":"Member Exists"}
```
=> Parse Mailchimp error message

.standard_todo.yml, app/admin/api/v3/resize_by_attribute.rb, app/controllers/api/v3/flows_controller.rb, app/controllers/content/tweets_controller.rb, app/models/api/v3/context_property.rb, app/models/api/v3/readonly/resize_by_attribute.rb, app/models/api/v3/resize_by_attribute.rb, app/serializers/api/v3/contexts/resize_by_attribute_serializer.rb, app/services/api/v3/flows/filter.rb, app/services/api/v3/flows/result.rb, db/migrate/20231004140255_add_parent_id_to_resize_by_attributes.rb, db/schema_comments.yml, db/structure.sql, db/views/resize_by_attributes_v_v02.sql, spec/services/api/v3/flows/filter_spec.rb
[Please include the link(s)](https://app.asana.com/0/home/1196034276163615/1205354181768983)
It is now possible to define a relationship between resize by attributes (units) in the CMS. Starting from the resize by / recolor by attributes you can add / edit a subunit and by setting a parent unit in the form.
The parent id is returned to the frontend in the /contexts endpoint; if a unit has a parent, it is a dependent unit and should not be allowed to be selected.:
When requesting flows for the parent attribute, the subunit values is also going to be returned as follows:
=> Returning flow values for extra cont attributes

frontend/scripts/react-components/tool-links/tool-links.initial-state.js, frontend/scripts/react-components/tool-links/tool-links.reducer.js, frontend/scripts/react-components/tool-links/tool-links.selectors.js, frontend/scripts/react-components/tool/sankey/node-interaction-utils.jsx, frontend/scripts/react-components/tool/sankey/sankey.component.jsx, frontend/scripts/react-components/tool/sankey/sankey.js, frontend/scripts/selectors/indicators.selectors.js
https://app.asana.com/0/1205165240647409/1205354181768983/1205660385178146/f
Display related indicators on the tooltip and not on the selection panel
=> Only display indicators without parent for select

frontend/scripts/app/helpers/splitLinksByColumn.js, frontend/scripts/react-components/tool/sankey/node-interaction-utils.jsx, frontend/scripts/react-components/tool/sankey/sankey.component.jsx
https://app.asana.com/0/1196306894127399/1205354181768983
Display links extra indicators on the sankey tooltip when links are hovered. Extra indicators are the indicators that have parent indicators and dont display on the selector
Go to the sankey (demo) - context: Indonesia - Wood Pulp
Select Total emissions in pulp wood concession indicator
=> Add extra link indicators
